### ISSUE TITLE
Add support for Zoom invigilation/live proctoring

### ISSUE THREAD

**Issue by MetromapSVG** [SafeExamBrowser/seb-mac#107]
My institution requires Zoom to invigilate students for online assessments, and to my understanding, this is possible on Windows.

I have been told so far that this feature is not available for macOS, and there is a significant student population that uses a Mac.

Much guidance is appreciated.

**Comment by danschlet** [comment]
There are discussions in our SourceForge forum about how to use Zoom with SEB for macOS, [see our support page for links to the old forums](https://safeexambrowser.org/support_en.html). In SEB 3.0 for macOS, you should theoretically also be able use Zoom directly in a web browser window, as WebRTC is supported (from macOS 11.1). Apple doesn't support the getDisplayMedia Web API though, so screen sharing with Zoom is currently neither possible in SEB 3.0 browser windows nor with the Zoom client running in background. The latter might will be possible in a future version of SEB for macOS.
We are also working on integrating Zoom for remote proctoring into SEB using the Zoom SDK. This will only work though for institutions which have a Zoom Enterprise account.

**Comment by danschlet** [comment]
The preview version of SEB 3.2 for macOS adds built-in Zoom support for proctoring. Currently this can only be used together with SEB Server (which anyways makes most sense).

See the [Releases section](https://github.com/SafeExamBrowser/seb-mac/releases) for the latest preview (or later the final) version.

**Comment by danschlet** [comment]
Built-in Zoom proctoring is available in a proprietary SEB Alliance Edition, due to licensing reasons. If you're interested in this version, contact the [SEB Alliance](https://safeexambrowser.org/alliance/join.html).
