### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-mac#11]
What security does SEB provide for local data? A certain company has a document "explaining" the superiority of an app based approach over a browser based approach on iOS. As far as I can tell SEB as a separate all should have its own encrypted sandbox, and should be as difficult to access the local data as it is in a native app providing local storage. The indexeddb storage file should be inside the SEB encrypted container. Providing all data is encrypted in transit, accessing the local data should be impossible? What about jailbroken devices? Can you provide some reassurance on the security compared to iOS native app solutions?

**Comment by danschlet** [comment]
We're currently using UIWebView in SEB for iOS, so data processed and stored by the web browser view will be as secure as the iOS architecture for UIWebView. On a device which isn't jailbroken, data should be secure. SEB refuses to run on jailbroken devices, but anything can be hacked as you probably can imagine.

To your question  "Can you provide some reassurance on the security compared to iOS native app solutions". No, we cannot. As our [MPL License](https://www.safeexambrowser.org/about_overview_en.html#license) states, SEB is provided as open source freeware "UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY OF ANY KIND".

Further discussion about security architecture is only available to paying members or donors of the [SEB Consortium](https://www.safeexambrowser.org/consortium/members.html).

**Comment by danschlet** [comment]
One addition: Some apps which claim to use a "superior" app based approach internally still use web views do display exam content. I even know of some exam software which is using code of SEB for macOS without officially admitting it. Don't believe statements of companies which are not transparent and use closed source code...

**Comment by keean** [comment]
> No, we cannot. As our MPL License states, SEB is provided as open source freeware "UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY OF ANY KIND".

Sorry if that was not clear, I was not asking about a warranty, but more if there is something like a white-paper which analyses the security issues.

> One addition: Some apps which claim to use a "superior" app based approach internally still use web views do display exam content.

Its exactly this sort of information that I was looking for. It would be really great if this could be captured in an engineering white-paper, so it could be given to potential users who have questions about the security. We can't all be security experts, so some considered views (independent and peer-reviewed would be even better) on this would be helpful to people making decisions about which solutions to go with.

**Comment by danschlet** [comment]
I was just citing the passage from the MPL License to make clear the nature of how we are providing SEB. 

An engineering white paper would surely be nice to have, but it would require significant resources to write it down. Maybe one day we'll have those, if more companies/institutions using SEB decide to contribute something back and become paying members/donors of the [SEB Consortium](https://www.safeexambrowser.org/consortium/members.html)... ;-)

**Comment by keean** [comment]
What membership level do we need to join the consortium?

**Comment by danschlet** [comment]
Most beneficial for most assessment companies is probably the Gold [Membership level](https://www.safeexambrowser.org/consortium/fees.html), as you get direct, personal consultancy by the SEB developers. We do answer single questions with a limited scope in the forum and or course comments to issue reports, but if an assessment developer/provider needs regular support or help for implementing/improving SEB integration in exam solutions, a Gold Membership makes sense. If you don't need such support, then with a Silver Membership level you can already suggest SEB development goals.

We will soon offer more incentives for the Gold or Principal Membership, for example you will be able to register a [Universal Link](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW1), so you could provide one URL or QR code to your users/customers to either install SEB from the App Store and/or directly open your exam system in SEB. Also companies wanting to build and distribute their own branded SEB version will be able to use a new security module which will require an API key.
