### ISSUE TITLE
SEB 2.1.2 Close Force Quit Window

### ISSUE THREAD

**Issue by Henrikko123** [SafeExamBrowser/seb-mac#12]
When opening SEB 2.1.2 in MacOS 10.12.6, it says it cannot run when the Force Quit window is open. I can still move the cursor, but the program itself is not working. The full error message is:
"Close Force Quit Window
SEB cannot run when the Force Quit window is open.
Close the window or quit SEB."
With two buttons "Quit" and "Retry".
When pressing "Quit", it quits. And when pressing "Retry" nothing happens.
How does this happen, and what may I do to fix this?

**Comment by Jeanvanberlo** [comment]
I'm also getting this error with macos 10.13.6 and seb 2.1.3. How did you solve it?
The force quit window isn't opened.

**Comment by danschlet** [comment]
Sometimes the operating system leaves some invisible window open which SEB identifies as the Force Quit window. If this happened while testing (very rarely), a reboot solved the issue. Please try that and let me know if it happens again.

**Comment by Jeanvanberlo** [comment]
A reboot resolved the issue. If I can reproduce it in some way I'll update this issue. Thanks!
