### ISSUE TITLE
Creating several SEB-Files on Mac

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-mac#121]
We are in the process of creating the final exams for next year with the SEB browser and an online Word file for each student, which will be entered as a link in the SEB file. (I didn't find any other solution for using Word (correction option) ...)
The configuration goes without any problems on Windows, because I have the Word files in Onedrive on one side and thus pick up one link after the other and insert it in the configuration tool and create an SEB file for each student.

This is problematic in MacOS. I have the SEB browser with the configuration window open on one screen and the Onedrive files from which I want to pick up the links on the other. The first link is not a problem: paste from the secured clipboard.
But if I want to get the second link, the SEB browser blocks all actions: for example, calling up the next link on Onedrive, copying it to the clipboard, etc.
Is there a solution for this?
Thanks for an answer.

**Comment by danschlet** [comment]
When you start SEB for macOS holding the Option / Alt key, it opens the Preferences window only and you can edit config files  easier, without applications in the background being blocked. Also you can set most settings of the macOS version also in the SEB Windows Configuration Tool, .seb config files are designed to be compatible with all SEB platform versions.

Also [see the manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html#configuration) (to be fair I just added this information to the manual, it was only mentioned in the release notes and news/download sections before).
