### ISSUE TITLE
SEB with Mac BigSur

### ISSUE THREAD

**Issue by brunobrandoli** [SafeExamBrowser/seb-mac#123]
Hello developers,

I am facing an issue for accessing the exams via Safe Exam Browser with Apple MacOS BigSur. Do you have any lead if the SEB 2.3.2 works properly with it? I tried many different potential tips, e.g. cleaning the cache, and did not work out.

Any idea if it works with the beta version 3.0 on MacOS?

Thank you.

**Comment by danschlet** [comment]
SEB 2.3.2 works perfectly on macOS Big Sur, as its release notes and the download page states.

You need to provide a way more precise description how it doesn't work for you. Or provide a video showing exactly what happens when you start SEB.

**Comment by danschlet** [comment]
If no further feedback received, this issue will be closed.
