### ISSUE TITLE
How to toggle language for SEB in Mac?

### ISSUE THREAD

**Issue by LimWeeKet** [SafeExamBrowser/seb-mac#13]
How to toggle language for SEB in Mac?

**Comment by danschlet** [comment]
Do you mean how to switch keyboard layouts (input sources)?
Use the option [Show menu bar](https://www.safeexambrowser.org/macosx/mac_usermanual_en.html#ConfigFilePane) and then the Input menu in the menu bar (the one with the country flag symbol). You have to enable the Input menu first in System Preferences / Keyboard / Input Sources /"Show Input menu in menu bar.

**Comment by LimWeeKet** [comment]
Is there any shortcut key to switch language in SEB? Normally is using “Command+SpaceBar” to switch.

**Comment by danschlet** [comment]
Which Mac OS version are you using? In recent macOS versions Command+Space invokes Siri or Spotlight Search.

Here I found some information how to set up shortcuts: [How can I set up a keyboard shortcut for switching input source?](https://apple.stackexchange.com/questions/135370/how-can-i-set-up-a-keyboard-shortcut-for-switching-input-source#135373)

**Comment by LimWeeKet** [comment]
OS X Yosemite Version 10.10.5
