### ISSUE TITLE
Crash on MacBook

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-mac#133]
Thank you very much for the support. I have a student with a MacBook OS version 10 who is experiencing an error that I have never experienced before. After a second the red screen appears, stays short and then the program crashes.
She doesn't have an antivirus that could block the connection. Here is a picture of what exactly is happening.
Thank you very much

**Comment by danschlet** [comment]
The error messages on the screen show, that the exam has not been correctly finished before (not using a quit link/Exit SEB button or the Quit button with quit password in SEB). This can happen if SEB crashes or the Mac is restarted or shut down (also if it runs out of battery) during a running exam. As that could be used to cheat before trying to re-enter the exam, SEB has this feature, displaying the red lock screen in such a case. As you can see in the video, this happened several times on 2021-09-14 and then the student tried to start the same exam (more precisely an SEB exam config with the same start URL) on 2021-09-21.
Normally SEB shouldn't crash after displaying this screen. To find out why it crashes, I would need the crash report which can be displayed with the "Bericht..." button in the alert "Safe Exam Browser wurde unerwartet beendet.". The text of the crash report can be copy-pasted into an e-mail or text document. I might also need to see the log files from the directory ~/Library/Logs/Safe Exam Browser/. This is in the normally invisible Library folder of the current user, the path can be entered in the Finder / Go / Go to folder... (Finder / Gehe zu / Gehe zum Ordner...) menu command to open the directory.

**Comment by dkummer63** [comment]
Thanks for the helpful information. Because it's a student who I don't see often, it takes a bit more time. 
Her MacBook actually crashed when she started it for the first time and the red screen has kept appearing ever since for only one second.
I suggest that she completely deletes the program and the associated folder and then try again with an installation.
We will look for the log file as soon as possible. So I hope that we can make progress with her Computer too. Otherwise, the program works well for the other 180 students.

**Comment by dkummer63** [comment]
Today I was able to reproduce the mistake on another mac and can give you more details. I first installed Version 2.3.2 and it crashed the first time the program started. Then I deleted the program, installed Version 3.0 and it crashed again and the red window was closed so fast, that I could not fill in the exit password. 
It is a MacBook Pro 12,1; MacOS Sierra, Vers. 10.12.6; Core i5; 
I attach the reportfile and hope, that you can help. We plan the final exam with the computers of the students and unfortunaltely many of the use Mac...
[Systembericht_27-1-2022.zip](https://github.com/SafeExamBrowser/seb-mac/files/7948653/Systembericht_27-1-2022.zip)
![vlcsnap-2022-01-27-08h59m14s656](https://user-images.githubusercontent.com/89595743/151316714-7f080419-9782-4a6f-ba85-5b023c8dc11d.png)
![vlcsnap-2022-01-27-09h00m36s173](https://user-images.githubusercontent.com/89595743/151316719-e4c8eb3f-4ad8-48fb-bfb7-860ab71ecd71.png)
![vlcsnap-2022-01-27-09h01m02s206](https://user-images.githubusercontent.com/89595743/151316720-01c3600b-93bd-4f0b-8c23-6e9757b17850.png)

**Comment by dkummer63** [comment]
10.13 is the lowest version on OS  that works with SEB.
