### ISSUE TITLE
Not able to use third party cookies in Seb for mac

### ISSUE THREAD

**Issue by AvikantSrivastava** [SafeExamBrowser/seb-mac#135]
I get message, looks like SEB doesn't support 3rd party cookies, is there a solution for this?

![image](https://user-images.githubusercontent.com/41926176/134985825-403c0959-92d3-459c-88fa-d6978640fe6e.png)

**Comment by danschlet** [comment]
We'll have a look if we can add a setting to loosen the browser's cookie settings. Generally web developers should avoid demanding third party cookies to be enabled, as privacy aware browsers like Safari block these by default.

**Comment by danschlet** [comment]
After finalizing SEB 3.1, we could have a look at this issue, but we would need some test access or test page/site to reproduce this. Do you have an idea what we could use for testing this?
