### ISSUE TITLE
SEB on MacBookAir

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-mac#136]
When one of my student work with SEB on a Mac Book Air, it starts with loud and strong fan noise for a long time. This leads to faster battery loss. Is it possible to do something against that? Thanks for answering.

**Comment by danschlet** [comment]
They should quit all unnecessary applications before starting SEB. SEB has to check the code signatures of applications which are running in the background (at least those which try to display foreground elements on the screen) and the according macOS API can take quite some time and CPU load for some applications, Xcode is such an example. 

Also using the AAC assessment mode on devices where it is available is an option, you would then need to [change the according setting](https://safeexambrowser.org/macosx/mac_usermanual_en.html#SecurityPane). But wait for the final release of SEB 3.0, as AAC works better there than in 2.3.2.
