### ISSUE TITLE
SEB for ios - problem with login

### ISSUE THREAD

**Issue by soohi12** [SafeExamBrowser/seb-mac#138]
Hello! I installed SEB and it was working just fine. Then, today, i tried to login with a file, but it doen't show te login box anymore. It just stays all white like the photo. Can someone help me?
![IMG_0032](https://user-images.githubusercontent.com/91974661/136065405-406ff16c-d3a6-46d6-9272-b0387d926cc9.PNG)

**Comment by danschlet** [comment]
Sounds like you're a student? Ask your exam provider (teacher, university, school, etc.). As we don't know anything about your exam, we cannot help.

**Comment by soohi12** [comment]
ok! Thank you!!
