### ISSUE TITLE
Permission to access my camera is always pop up every time I reload the page (SEB 3.0)

### ISSUE THREAD

**Issue by jespermartinez** [SafeExamBrowser/seb-mac#140]
Hi, I like this version of SEB 3.0, but I have a small problem regarding the permission to access the camera. Why its always showing up on my end every time I reload the page for the next question. I think it's very annoying to our students during their exams.

Is there any way to show it at once after pressing the "allow" button? and the same feature's functionality on Windows? By the way, I am using macOS Big Sur v-11.6 

Thank you :))

![121212121212](https://user-images.githubusercontent.com/57584088/137096283-ea69ae2a-2800-419c-9358-571fc4d2fbd0.PNG)

**Comment by danschlet** [comment]
Fixed in SEB 3.1.1 when running on macOS 12 Monterey.
