### ISSUE TITLE
minMacOSVersion for 10.13 and 10.14

### ISSUE THREAD

**Issue by benjaminwols** [SafeExamBrowser/seb-mac#148]
I notice that minMacOSVersion does not work for enforcing 10.13 and 10.14.

In `seb-mac/Classes/SEBController.m` the case statements only go to SEBMinMacOS10_12. It seems SEBMinMacOS10_13 and SEBMinMacOS10_14 are forgotten.

There is also a typo in the documentation of the configKeys (https://www.safeexambrowser.org/developer/documents/SEB-Specification-ConfigKeys.pdf). On page 23 it specified 10_12 twice. The second one (7) should be 10_14 (see screenshot).
<img width="262" alt="Screenshot 2021-11-04 at 10 45 10" src="https://user-images.githubusercontent.com/12526288/140292268-15e8623b-9417-4ab6-81cf-d4bbf1107ab4.png">

**Comment by danschlet** [comment]
This should be fixed in SEB 3.0 for Mac. Its code is currently in the branch 3.0_unified. We will clean up the probably confusing branches in the next few weeks.
