### ISSUE TITLE
Feature request for iOS: XML association

### ISSUE THREAD

**Issue by joseluisrc** [SafeExamBrowser/seb-mac#149]
Dear SEB developers.

I've been having an issue with iOS (iPhones and iPads) where de .SEB file is detected as an XML and iOS automatically renames it to .XML. Since the Safe Exam Browser app isn't associated with .XML files, you can't open the config file.

The curious thing is that it doesn't always happen, so it's not easy to debug. The .SEB files are edited using the Config tool and no manual changes are made. Some files are opened without any problems and other times it's detected as an XML file.

I think the easiest workaround would be to associate the app with .SEB and .XML file types, since it's impossible to rename file extensions in iOS, unless you use a third-party file managing app to rename it.

Thanks!

**Comment by joseluisrc** [comment]
After I sent this request, I discovered what seems the root of the problem.

It seems that if you share the .SEB file through a Google Drive, it is served as an application/xml. If you share it through another service, like Dropbox, it's served as an application/seb.

**Comment by danschlet** [comment]
Unfortunately it's still not easy (or not possible without third party software) to change file types of downloaded files on iOS, so I guess you won't be able to use Google Drive for sharing SEB files. I'm using iCloud Drive (with the Files app) which works well. 
I would be cautious to add an application/xml file type association to SEB, as it might create issues when this file type is supposed to be used with another app. Or do you think that wouldn't be a problem (as people could still choose the app with which to "share"/open the file)?
