### ISSUE TITLE
Mac OS Monterey (12.0.1) issue with VMware Horizon

### ISSUE THREAD

**Issue by ndum** [SafeExamBrowser/seb-mac#150]
Hello!

After updating to Mac OS Monterey (12.0.1), logging into VMware Horizon (8) HTML Access no longer works with the SEB.

After entering the login data, it simply hangs. The login also does not get through to the view console.

This occurs with version 3.0 and also with the current preview (3.2. pre2).

Thanks for any support.

**Comment by sbaerlocher** [comment]
Hi
i have the same problem, are there any fixes?
Thanks!

**Comment by danschlet** [comment]
Thank you @ndum for investigating the issue further! This kind of precise information helps us a lot when trying to solve issues (especially when we're busy working on releases or other issues).

Current versions of SEB on Mac use the system provided version of the WebKit framework (library). This is determined by the macOS operating system version and not the Safari version installed. Safari uses an own, embedded WebKit version, especially when running on the two older macOS versions Apple usually supports (current Safari versions run on macOS 10.15 Catalina,  11 Big Sur and 12 Monterey of course, maybe still also on 10.14).

So it's possible it will work again with macOS 12.1 or 12.2, if Apple updates WebKit to the one in the tech preview.

Maybe it also would work when switching to the classic WebView (see Preferences/Browser), although the modern WebView surely has some performance and stability advantages.

**Comment by ndum** [comment]
Hi @danschlet

Thanks for the detailed answer. Unfortunately, switching to the classic webview did not help.

I think we have to wait for the Apple updates.

**Comment by ndum** [comment]
Hi, just a status update:

Unfortunately, Safari 15.2 is now also provided as an update on older Mac versions (e.g. Big Sur) and breaks HTML access there as well.

Waiting for Safari 15.4 is still the only solution...

**Comment by danschlet** [comment]
Hi @ndum, thanks for the status update.
I'm trying to get SEB to use an embedded WebKit build, for other reasons (to be able to support web-based screen sharing with the getDisplayMedia() API, which Safari supports, but not the macOS-provided WebKit framework/library). I got stuck when I tried it some days ago, I will continue with that after the holidays. That should theoretically solve this issue, when it would work with the Safari nightly builds which will be used by Safari 15.4.

**Comment by ndum** [comment]
Hi @danschlet

Any news with the embedded WebKit build? Unfortunately the problem still exists.

Thanks!

**Comment by danschlet** [comment]
I wasn't successful in adding an embedded WebKit build until now and unfortunately didn't get any information from WebKit developers about how to possibly solve it. I'll have another look at it when SEB 3.1 is otherwise ready to be released in a few days.

**Comment by ndum** [comment]
Hi @danschlet

Good News: With Mac OS 12.2.1 (Safari 15.3) and Horizon 2111 its working now.

Thanks for your support.
