### ISSUE TITLE
Fix keyboard shortcuts for page/text zoom and reload in SEB 3.0 for macOS

### ISSUE THREAD

**Issue by danschlet** [SafeExamBrowser/seb-mac#157]
Problem: **Even though "Allow reload" is disabled for both the Exam Window/Additional Windows, both "Cmd + R" and using the reload command from the "View" drop-down on the menu bar still allow the page to be reloaded.** This is problematic for our test since our testing system will automatically boot a student out of the test and require a resetting process by a testing administrator if the page is reloaded in the middle of their exam. 

Additionally, **both page and text zoom are enabled and the "zoom in/out" commands can be clicked on in the "View" drop-down, but neither the keyboard shortcut or "View" drop-down actually zoom in/out on the browser page.** The OS recognizes that the keys are being pressed to zoom in/out but not actually doing the action. That being said, if I enable the "browser window toolbar" in "User Interface", the buttons that appear for increasing/decreasing page and text zooms work fine, it's just the keyboard shortcuts and View menu that are non-functional even though they appear normal. 

Tested this on a Macbook Pro and the issue was replicated in Big Sur (11.6.1), Catalina (don't remember exact version) and Mojave as well.

_Originally posted by @BT-testsupport in https://github.com/SafeExamBrowser/seb-mac/discussions/154_

**Comment by danschlet** [comment]
These issues were fixed in the [SEB 3.2pre4 pre-release version](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.2pre4). Besides what is listed above, also back/forward navigation using cmd-Cursor left/right was possible. 

SEB 3.2 only runs on macOS 10.14 Mojave or newer, we will back port these fixes to SEB 3.1 though.

**Comment by BT-testsupport** [comment]
Thanks so much for the quick work on this! Might not have time to test it out till late today/early tomorrow but will make sure to let you know if I run into any issues when I do.

**Comment by BT-testsupport** [comment]
Installing and using the 3.2 pre-release did the trick (at least on a laptop with Big Sur, haven't checked other use cases)! Didn't run into any of the zoom/keyboard shortcut issues that popped up in 3.0.

**Comment by nvarghese-rm** [comment]
Hi @danschlet - To address the zoom issue, just wondering when you may port back the fixes to 3.1 or when v3.2 will be formally released please?

**Comment by danschlet** [comment]
3.1 will be released in January. Happy new year until then...

**Comment by nvarghese-rm** [comment]
@danschlet - Hi , It was reported to me today that the keyboard shortcuts for zoom work on MAC OS Monterey v12.
It wasn't working for me and I was on Mac OS Sierra v10.13.  So some differences there between OS versions.
