### ISSUE TITLE
Issue with Inspect Elements Safe Exam Browser V3 - OSX

### ISSUE THREAD

**Issue by aidandauphin** [SafeExamBrowser/seb-mac#159]
We have been testing the latest release of Safe exam browser V3 for OSX. Part of the reason we are needing to test as we need to incorporate our inVigilation software.

We are experiencing an issue with incorporating our eVig with SEB. For this, we have enabled the following...
* Hooked Keys - 'Enable Right Mouse (also Mac*)
* Enable Web Inspector (developer tools)

* I right mouse click, 'Inspect elements'

All I get is the screen flickering, unable to see the inspection box due to the flickering.
* Unable to cancel this action, only way out is to quite SEB
* You can hover the mouse over the elements you see the box appear and then goes away.
* Have tried 'Links requesting to be opened in a new browser window.....' Action = Open in new window
* Select Browser Engine Policy 'Prefer Modern'
* Tried on Windows, this works as expected

Any help/suggestions would be greatly appreciated.

**Comment by adrianwhatwedo** [comment]
I had the same issue with the inspect element function and inspecting the elements was not possible. 
The screen flicker did not go away and only restarting SEB helped. 
Using SEB V3 with MacOS Big Sure 11.3

**Comment by sudharsans85** [comment]
We too are facing same issue with latest SEB for MacOS. Screen just keeps flickering 
Is there any other workaround or setting to be enabled?
Our website is not working fine in SEB Mac alone - we need access to developer tools to troubleshoot it further

There is no issue with SEB Windows version & it provides entire developer tools access 
In Mac, Will it show console/network tab also or just elements tab

**Comment by marcwieland95** [comment]
Can confirm that issue too in macOS Big Sure (11.5.2).
Flickering and unusable web console. Would be nice to debug and develop certain things on the Mac version

**Comment by danschlet** [comment]
This is briefly mentioned in the release notes:
https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.0

Setting to enable WebInspector (developer tools) and remote inspection (only when running a debug build) is now functional in WKWebView, although the "Inspect Element" context menu (right mouse click must be enabled in settings as well) doesn't work correctly with WKWebView.

Apple doesn't support Inspect Element in the modern embedded browser engine (WKWebView), you can only build SEB in Xcode and connect Safari with activated Debug menu to the running SEB instance. There is a WWDC video showing this, but it is no longer available on Apple's developer website (search YouTube for WWDC 2014 WKWebView or WebKit or so).

We'll create an Apple Feedback asking them to make this available, you can do the same.
