### ISSUE TITLE
SEB with MacOS

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-mac#170]
Hello and thank you for your service!
I am testing an online Word solution with the SEB at our school and a problem arose here with a student. She has a MacOS X 10.11.6. (Version).
Starting with SEB the components of the Onlineword do not load completely. See image. Even restarting several times did not help. 
I know a similar problem from other Mac computers. In some cases with online Word, for example, the correction module does not load, but if you reload the page, everything is well. 
But here it does not load almost anything. This is new and a bit unsettling. Do you have any advice on how I could proceed?
Many thanks and best regards
Daniel
https://user-images.githubusercontent.com/89595743/145415212-a8deafc7-cc64-41dc-8ebd-11655dfe5a09.jpg

**Comment by danschlet** [comment]
Was SEB 3.0 used? Maybe you changed settings which cause these issues. To rule that out, you could try the online word solution with SEB default settings. I also suspect that the classic WebView (WebKit browser engine) might not be compatible with that online word solution (I know that Microsoft Forms doesn't work with it). In that case you would need to make sure that your settings allow SEB to use the modern WebView, see details in [SEB 3.0 release notes](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.0).

**Comment by dkummer63** [comment]
Thank you for your answer. The student uses SEB 3.0 an also with the default settings there was no difference. She is the only one out of 200, so we can handle it, but when you have another idea I would be thankful.

**Comment by danschlet** [comment]
Btw. macOS 10.11 is very old. I suggest you ask students to use at least macOS 10.13 or better one of the three latest versions which still get security updates from Apple, which would be macOS 10.15, 11 and 12.

**Comment by dkummer63** [comment]
I advised the students, that 10.13 is the lowest version, that is supported. Thank you for your answer and all the best!
