### ISSUE TITLE
Safe Exam Browser 3.0 Xcode

### ISSUE THREAD

**Issue by egebartukurtaran** [SafeExamBrowser/seb-mac#171]
Hello, 
I cloned the seb-mac 3.0 unified version and i tried to build the project on xcode. However, whenever i build the project, i get an error as Library not found for -lmbedtls . I'm very new for objective-c and xcode. What should i do for building and running the program correctly ?

![Ekran Resmi 2021-12-10 12 51 01](https://user-images.githubusercontent.com/92180621/145554181-a85d08cd-0e39-4c03-97f8-2159c9611059.png)

**Comment by danschlet** [comment]
I'm sorry, for resource reasons we cannot give support for building your own version of SEB. We provide that support only to Platinum (and exceptionally to Gold) contributors of the [SEB Alliance](https://safeexambrowser.org/alliance/fees.html).
