### ISSUE TITLE
SEB MacOS config misses "Ignore errors when validating display configuration" setting (and perhaps others)

### ISSUE THREAD

**Issue by jeroenhabets** [SafeExamBrowser/seb-mac#172]
SEB Configuration Tool for Windows contains a "Ignore errors when validating display configuration" setting. I could not find it in SEB for Mac (3.2pre5).

Reporting this example as we ran into it during our MacOS and VirtualBox+Win tests.

**Comment by danschlet** [comment]
The Windows Config Tool and Mac Preferences until now never were perfectly in sync, as we couldn't sync our releases for resource reasons. This should happen in 2022 though. 
The crash in the Config Tool you reported shouldn't happen though, and SEB 3.2pre5 being a pre-release isn't complete yet. Stuff like Windows Preferences options usually are done in the very end after all Mac functionality is working...
