### ISSUE TITLE
"Quit" in "Force Quit" dialog does not quit (infinite loop)

### ISSUE THREAD

**Issue by jeroenhabets** [SafeExamBrowser/seb-mac#173]
For some reason I got the "Force Quit" dialog, I clicked "Quit"

EXP: SEB quits
ACT: SEB dialog momentarily disappears and then reappears again. (ad infinitum)

<img width="270" alt="image" src="https://user-images.githubusercontent.com/1929535/147746339-da74e7f9-269b-4263-b44b-67826fee5b85.png">

[Edit] Apologies, missing info supplied:
SEB: [SEB Mac 3.2pre5](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.2pre5)
Mac OS: 12.0.1 (MBP 16" 2019)

**Comment by danschlet** [comment]
Can you please ALWAYS indicate the exact SEB version you observed that and the macOS version used? Thanks.

**Comment by jeroenhabets** [comment]
@danschlet Apologies, description updated with missing info:

SEB: [SEB Mac 3.2pre5](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.2pre5)
Mac OS: 12.0.1 (MBP 16" 2019)

**Comment by jeroenhabets** [comment]
@danschlet I might have found the cause for my issue: There is actually no "Force Quit" dialog open but rather a "server connection interrupted" dialog with "Ignore" and "Disconnect all".

Screenshot failed (as it should with SEB) but it looked a like:
![image](https://user-images.githubusercontent.com/1929535/149091087-169fceb9-7b99-436f-bc80-df6044699475.png)

**Comment by danschlet** [comment]
The Close Force Quit dialog in SEB definitely didn't work correctly, it should be fixed in the latest preview 7 of SEB 3.1: https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.1pre7.

I also updated the text to "Force Quit window or another system frontmost dialog".

**Comment by jeroenhabets** [comment]
@danschlet Thanks! and FWIW I can confirm I can no longer reproduce it using SEB 3.1.1 142B2 on macOS Ventura 13.0.1 (22A400)
