### ISSUE TITLE
Can't use fullscreen with MacOS 

### ISSUE THREAD

**Issue by jaenu0** [SafeExamBrowser/seb-mac#178]
We use SEB for our tests but the students who use Mac can't use SEB in fullscreen mode. Attached is a picture where the issue occurs. When they click on the button to enter fullscreen mode, nothing happens. 

Macs:
MacBook Air 2015 (Intel i7)
MacBook Pro 2021 (M1 max)
MacBook Air 2021 (M1)

OS versions: Big Sur 11.0.1 & Monterey 12.0.1

Is there a way to make it work because they can't work on such a small window. 

![IMG_4036](https://user-images.githubusercontent.com/98152379/150497631-55dc1053-fc07-4e66-aadb-a5b20b0829e5.jpg)

**Comment by danschlet** [comment]
It might be that this would work when SEB can use the modern WebView. But in Moodle, this will only be possible with the updated Moodle-SEB integration, which will be available in Moodle 4.0.

**Comment by danschlet** [comment]
A limited full screen support is now available in SEB 3.1.1 release candidate (please test). See #226
