### ISSUE TITLE
Pop-Up of a word office online not possible

### ISSUE THREAD

**Issue by kollbrt** [SafeExamBrowser/seb-mac#183]
Hi there,
Same problem we (Berufsmaturitätsschule Winterthur) have already reported for Windows SEB: in the newer versions of SEB for Mac (and win) we cannot open a pop-up file, that we put in an exam on OpenOlat. From there, the docx file normally opens in a pop-up window and opens microsoft office online. In the older version (till SEB 2.3.2 for mac), we were able to open the files on some mac but not on all of them.
I just wanted to ask, if there is something on the way in an update, so this issue would be solved?
The second problem is, that mac user can still switch to other programs by putting cmd and tab (I made for both issues a video - you find it here: https://photos.app.goo.gl/4MjMxbVt2pMP8VhY7). Is this problem a wrong configuration of my SEB or is it an SEB issue?
Thank's for your help.

**Comment by danschlet** [comment]
Regarding the first question, you have to make sure that the modern WebView is used, [see release notes of SEB 3.0](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.0). Also try it with the [current preview version of SEB 3.1](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.1pre9), as various web browser engine related issues are fixed there. In general, we cannot help with using particular web applications, as long as there is no clearly identified SEB bug, which we can ourselves reproduce (we need a testing access to such a system and clear step-by-step instructions how to reproduce the issue).

You need to read warning messages when they pop up, also the manual describes why you cannot use the feature [Allow switching to third party applications](https://safeexambrowser.org/macosx/mac_usermanual_en.html#PermittedProcessesSection) in secure exams (it's only usable in fully open book exams or for debugging SEB).

**Comment by kollbrt** [comment]
Is there a possibility that we hire someone of you SEB-people for a day or some hours? And if yes, how much would it cost? 
We really would like to have a working set up with SEB and OpenOlat for the final exams of our students. And it would be great to have some support.
If you want to reproduce the issues I reported, then I could send you by mail an account of our OpenOlat platform.

**Comment by danschlet** [comment]
I can refer you to the FAQs of the SEB Alliance (but that applies to us SEB developers generally):

[Does the SEB Alliance offer contract work?](https://safeexambrowser.org/alliance/faq.html#collapse15)
No, the Alliance does not offer contract work neither in the consulting area nor in the field of SEB software engineering. Please note that the SEB Alliance is not a company. The Alliance is solely devoted to the SEB open source project which requires ongoing funding to continue its maintenance, development and support activities.

But [OpenOLAT/frentix are Gold Contributors to the SEB Alliance](https://safeexambrowser.org/alliance/members.html). If this Microsoft Office online is a built-in or often used feature in OpenOLAT, you should contact frentix for help and they can discuss how to solve this issue with us. 

We are only responsible for SEB development and don't use OpenOLAT ourselves, therefore someone with technical experience with OpenOLAT should lead this.
