### ISSUE TITLE
"CMD + F" Search functionality not working.

### ISSUE THREAD

**Issue by milleva** [SafeExamBrowser/seb-mac#187]
The University of Helsinki's law department have cancelled the use of computers in their coming up exams because Mac users can't use this feature. Very unfortunate.

Not yet sure if it is a bug in code or a missing feature but "cmd + f" key combination does not work as "ctrl + f" does in the Windows version. Taking a quick look myself. Codebase is completely foreign to me but hopefully I can provide a lead at least.

**Comment by danschlet** [comment]
This feature is about to be implemented for the final release version of SEB 3.1.

**Comment by milleva** [comment]
Thank you for the quick response and sorry for the annoyance. This issue can be closed on my part. Would you have a ballpark-estimate for when 3.1 could be released? Cheers.

**Comment by danschlet** [comment]
There is a release candidate version for SEB 3.1 available, [for the download](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.1rc) see the [Releases section](https://github.com/SafeExamBrowser/seb-mac/releases) of the seb-mac repository. You can get notified about beta/prerelease versions by watching the according sections in the SEB repositories here on GitHub and about important beta/prerelease we sometimes also inform on our Twitter handle and RSS news feed.

**Comment by danschlet** [comment]
This was included in SEB 3.1 for macOS and iOS. The browser engine in iOS doesn't support search in PDF files (at least it wasn't up to iOS 15). We may be able to implement support for search in PDFs also on iOS, but that needs to wait for a future release due to lack of resources.
