### ISSUE TITLE
Problem with webcam access on Mac OS

### ISSUE THREAD

**Issue by NicoleLewin** [SafeExamBrowser/seb-mac#189]
Hello everyone, I have the following problem. I use the Safe Exam Browser in combination with Moodle. Before a student starts the exam, he has to download the configuration file. After downloading the file the Safe Exam Browser starts then who starts the test. Before he can start the test, he has to agree that the webcam can take pictures of him. This is where the problem occurs. On Windows, the webcam image is now displayed in a pop-up window with the system message in small. On Mac, however, this is not displayed, so the student can check the box but cannot start the test.
What is the reason that access to the webcam is blocked?
If the student starts the test without downloading the configuration file first, then the webcam can be accessed.
Is there anything I need to do in the configuration file to make the webcam access work?

I use the seb version 3.0 and the MacOS Monterey 12.1

Many thanks in advance

**Comment by danschlet** [comment]
See this https://github.com/SafeExamBrowser/seb-mac/issues/66.
