### ISSUE TITLE
push notifications

### ISSUE THREAD

**Issue by antton** [SafeExamBrowser/seb-mac#19]
Hi, 

I'm trying to integrate https://onesignal.com/ in my LMS but as it's working properly with firefox, chrome and safari, when I try to use it with safe exam browser i can't get notifications working.

Could you tell me how to debug with SEB? In that way I can check what is blocking my web connections and so on..

Thanks for your works!!

**Comment by danschlet** [comment]
Hi,

One of the purposes of SEB is to block all kinds of communications from the outside, including all kinds of notifications. SEB as a kiosk system allows restricts access to information directly provided by the exam in a web browser view. So it generally doesn't make sense to allow web (or any other) notifications to be displayed, then SEB would need to filter out all notifications unrelated to the exam.

In addition, the macOS notification display system (which I guess all browser use) is anyways blocked by the macOS kiosk mode API (NSApplicationPresentationOptions). So it anyways wouldn't be possible to allow some notifications.

I don't understand your use case (what kind of notifications do you need to display during an exam?), but probably you can achieve something similar by displaying an overlay popup inside the browser window, implemented using some Javascript/AJAX magic.
