### ISSUE TITLE
SEB Reset Error Message

### ISSUE THREAD

**Issue by tommyday** [SafeExamBrowser/seb-mac#2]
I used Casper Composer to capture the customized org.safeexambrowser.Safe-Exam-Browser.plist file and then deploy this to all my users laptops. That process works and the file gets deployed properly. Whenever we launch the program we get an error message (attached), but after clicking "OK" SafeExambrowser works perfectly with all the custom settings. Any idea of how I can get rid of this messages for my students?

![se reset](https://cloud.githubusercontent.com/assets/7860280/20273682/3e2c7924-aa60-11e6-87a4-0e54f0d5658a.jpg)

**Comment by danschlet** [comment]
Which version(s) of SEB are you using? Please ALWAYS indicate this!

The behavior you're describing doesn't make sense. It is correct that SEB doesn't allow to be configured by copying/deploying the org.safeexambrowser.Safe-Exam-Browser.plist file to other computers. See the [manual](http://safeexambrowser.org/macosx/mac_usermanual_en.html#configuration), I copied the relevant section below. You need to deploy a configuration file named SebClientSettings.seb into the Preferences folder.

So the error message is expected, but definitely the after clicking OK SEB shouldn't work correctly with all the custom settings, as its settings are reset to default settings when this error message is displayed.

Or are you starting exams by opening a SEB config file saved with the option "... for starting an exam" (locally or using a seb(s):// link to that .seb config file? Then you anyway wouldn't have to configure the local (persistent) settings of SEB.

Please check if your SEB clients are really using the custom settings from the deployed org.safeexambrowser.Safe-Exam-Browser.plist file, by starting the SEB application directly from the Applications folder. As mentioned, this shouldn't be the case, at least not if you don't also deploy the encryption key for those local/persistent settings (which is stored in the macOS Keychain).

> Local client settings are saved according to macOS standards in the user's Library/Preferences/ directory (~/Library/Preferences/, is by default invisible in Finder). Starting SEB version 2.0, it isn't anymore possible to deploy the org.safeexambrowser.Safe-Exam-Browser.plist file from the Preferences folder to other machines (due to stronger, individual encryption per client). Instead, either deploy and open a .seb config file saved with the option 'Use SEB settings file for ... configuring a client'. This requires user interaction, because SEB will show an alert 'Local settings of this SEB client have been reconfigured. Do you want to continue working with SEB now or quit?' and one of the buttons 'Continue' or 'Quit' has to be clicked. As an alternative, you can use the new pre-configuration feature when deploying SEB on managed systems which works similar like in SEB for Windows (and doesn't require user interaction):
> 
> While starting, SEB now checks if there is a configuration file named SebClientSettings.seb in in the Preferences folder (~/Library/Preferences/) and reconfigures itself silently (no user feedback) to the settings in that file, then the file is deleted. This works only if the administrator password in this file matches the one set in the local settings of the SEB client or if there isn't an administrator password set yet in the local settings. This means, if the SEB clients haven't been configured before (because SEB just got installed), you can set an arbitrary administrator password in the SebClientSettings.seb file. The second time you reconfigure SEB clients with this method, the administrator password in the new SebClientSettings.seb file has to match the one used before, otherwise the client won't be reconfigured. The file can either be unencrypted or encrypted with a password that matches the administrator password set in the local settings of the SEB client (otherwise the password to decrypt the settings file will be prompted and the user has to enter it).

**Comment by tommyday** [comment]
Daniel, forgive me, I looked right at the instructions asking for the version and rushed through it, neglecting to post the version. I am using version 2.1.2. Thanks for the manual link, I am reading through it now about the settings file and will retest how I deploy this. Also, I tested this on another machine and you are correct, "SEB doesn't allow to be configured by copying/deploying the org.safeexambrowser.Safe-Exam-Browser.plist file".
heading off to work more on this, thanks Daniel.
-Tom

**Comment by tommyday** [comment]
This is working really well now with deployment, thanks for getting me down the right path! Follow up question from my user. We have it set with a quit password but thought that was just if the student wanted to quit the test prematurely during the test. The student had to enter the quit password even when completing the test and trying to exit. Is that working as deigned?

**Comment by pawy** [comment]
Its possible to configure SEB to quit after the exam is submitted without having to enter a quit password by specifying a quit link and placing this on the summary page displayed by the LMS after submitting the exam.

**Comment by tommyday** [comment]
Got it, thanks. Final piece I am looking for (i think!) is how and where to
edit the summary page, i don't see it in the SafeExam prefs?

**Comment by pawy** [comment]
With summary page i meant the page that you show your student when the exam is done.
Something like:

"Thank you for taking our test. To end the exam press here [quit-link]"

It's not a page provided by seb, rather by the system your exam runs on.

If you are not able to edit that page, then you cannot place a quit-link there.

**Comment by danschlet** [comment]
> If you are not able to edit that page, then you cannot place a quit-link there.

This is true. But you can set the URL of the summary page as quit URL/quit link. Then SEB will quit as soon as this page is loaded by the exam system. For this to work the URL of the summary page needs to be unique and always the same for that exam. You have to enter the full URL of that page exactly as it is displayed (in another browser).
