### ISSUE TITLE
Crash To Homescreen

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-mac#20]
We experienced issues with SEB for iOS crashing for a few candidates in a recent sumative exam for about 300 candidates. One candidate had their ipad crash more than three times during the exam. What is the best way for us to help you debug these issues?

**Comment by danschlet** [comment]
On the iPads where SEB for iOS crashes, "Share iPhone Analytics" and "Share With App Developers" should be enabled (Settings/Privacy/Analytics), then I get the crash reports automatically (only anonymous crash reports, there is no data to identify a device or a user). Ideally send me the date and time when these crashes happened (maybe Developer Analytics were active on some of these devices?), then I might be able to identify the crash reports.

**Comment by keean** [comment]
Do you know if this can be enabled for Safe Exam Browser through the MDM? These are candidates devices that they bring to the exam.

**Comment by danschlet** [comment]
It seems that some MDM solutions support that (after a quick Internet search), even though I didn't see the setting in Apple's Profile Manager.
