### ISSUE TITLE
iPadOS 15.4.1 update causes weird SEB 3.0.1 behavior

### ISSUE THREAD

**Issue by RoChess** [SafeExamBrowser/seb-mac#205]
This does not happen on an iPad Mini 5th gen, and seems to only relate to the larger iPad/iPad-Pro models.

Loading SEB configuration works via URL, manual entry, or QR-code, tried both https:// and sebs:// schemes.
Logging into LMS works
Opening course -- this is when SEB 3.0.1 crashes to desktop

iPad Mini (5th generation), model MUQW2LL/A == everything works
iPad (9th generation), model MK2L3FD/A == fails when something as simple as opening course is done, and crashes to desktop

Only have physical access to the iPad Mini, so that makes testing difficult, but I can get logs from the iPad 9th gen owner if needed.

Multiple iPad Pro users started to complain this week, which led to the deeper dive. Based on anecdotal evidence from users it seems to have started in the last two weeks which seems to correspond directly with Apple's iPadOS 15.4.1 release. Those same users had no issues last year, or earlier this year. All users that complained have confirmed they got the non-mini version.

**Comment by danschlet** [comment]
We can hardly reproduce such an issue, but I'll keep observing the crash logs from devices which share diagnostic data (anonymously). Until now I didn't see an uptick of crash logs from devices running iOS 15.4.1.

It would be helpful to test if it also happens with the 3.1 iOS beta. Although if it's a web engine related crash, the 3.1 update would not necessarily solve it, especially if your testing web app uses the classic WebView in SEB.

**Comment by RoChess** [comment]
> It would be helpful to test if it also happens with the 3.1 iOS beta. Although if it's a web engine related crash, the 3.1 update would not necessarily solve it, especially if your testing web app uses the classic WebView in SEB.

Do you have a TestFlight invite code?

**Comment by danschlet** [comment]
https://testflight.apple.com/join/egxLmc4j

We often mention new beta releases on Twitter or in our RSS feed and some specific GitHub issues or discussions.

**Comment by RoChess** [comment]
Thanks, I was actually able to crash it rarely on the iPad Mini myself on 3.0.1, but my co-worker send in three separate crash logs. Turns out we did not had that option active on either of our iPads, so that should be sending the logs to you hopefully. I'll be happy to share the reproducible steps in private otherwise as it will contain login credentials.

**Comment by danschlet** [comment]
Closed for lack of feedback.
