### ISSUE TITLE
Microsoft Forms not loading on macOS

### ISSUE THREAD

**Issue by csuterkzn** [SafeExamBrowser/seb-mac#208]
I encountered a problem previously mentioned in the old sourceforge tickets 66 and 100 (link below): Microsoft Forms is not loading as a starting site on Mac in SEB 3.0. Since the replies to the previous tickets mentioned that the issue will be resolved in SEB 3.0, I thought I'd report that unfortunately it's not working.

https://sourceforge.net/p/seb/support-requests/66/
https://sourceforge.net/p/seb/bugs/100/

**Comment by danschlet** [comment]
I didn't test it with SEB 3.0, but it definitely works with the release candidate of SEB 3.1, [for the download](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.1rc) see the [Releases section](https://github.com/SafeExamBrowser/seb-mac/releases) of the seb-mac repository.

You need to make sure that your settings allow to use the modern WebView (see [Release Notes of SEB 3.0](https://safeexambrowser.org/macosx/mac_release_notes_en.html), in SEB 3.1 you can confirm that the modern WebView is used by trying pinch-to-zoom on a trackpad).

**Comment by danschlet** [comment]
Also don't change SEB settings from their default values where you're not 100% sure you understand their function and that you need to change it. So if it still doesn't work with your existing setting, create new default settings and change only the Start URL to test if it basically works.

**Comment by csuterkzn** [comment]
Thanks for the swift reply! It does indeed work with the default settings. After some testing, the problem seems to be caused by ticking the Activate URL filtering option.

**Comment by danschlet** [comment]
Welcome. Yes, when using the modern WebKit browser engine (WKWebView), SEB currently doesn't support URL content filters (only URL filters for links and page loading). So if you enable "Activate URL filtering", but not "Filter also embedded content", this would still work with the modern WebView (which is required for Microsoft Forms). But you of course would need to make sure that the URL filters you define don't block some URLs needed for Forms to work correctly (which can be tricky).
