### ISSUE TITLE
Keyboard fails to fully open

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-mac#21]
In a recent summative exam, using iPad minis, we had several candidates (maybe 5%) with a problem where the onscreen keyboard failed to open properly, just revealing a grey rectangle, instead of the keyboard. At this point we could not continue the exam, nor could we exit SEB. Is this a known problem, and what could we do to help debug the issue?

**Comment by danschlet** [comment]
I will investigate this, I never heard of the problem before. Which iOS version was running on these iPad minis? Maybe it's a known issue on iPad mini. SEB itself doesn't handle the on-screen keyboard, iOS handles it. So this issue might happen in other apps too, maybe it's related to the Automatic Assessment Configuration single app mode (I guess you're using that and not ASAM on supervised iPads).

**Comment by keean** [comment]
These were iPad mini-2s they should have all been running the latest iOS (11), as this was checked using the MDM. They were configured using the MDM, so they were supervised, and I guess would default to ASAM when they lock themselves down.

This might be related to another issue, where some pads got very slow, one taking over 30 seconds to respond to a scroll event. I was wondering whether background processing or app-update could be slowing them down, and if SEB could forbid background processing/updates whilst it is in secure mode?

**Comment by danschlet** [comment]
"if SEB could forbid background processing/updates whilst it is in secure mode": No, iOS doesn't offer such APIs, in general apps hardly ever can do any kind of changes in the operating system, as iOS uses this very strict sandboxing model. I'm also not aware of any such MDM functionality. Would be interesting to analyze device logs to possibly find out the source for this slow down. But for that such a device would need to be connected to a Mac with Xcode and for non-developers it's probably not easy to get the relevant logs.

**Comment by danschlet** [comment]
SEB needs to be set in the MDM as an allowed App to switch on ASAM, then it is used, otherwise it's still AAC. If users don't get the question if they allow SEB to lock their device, then ASAM is used.

**Comment by keean** [comment]
> But for that such a device would need to be connected to a Mac with Xcode and for non-developers it's probably not easy to get the relevant logs.

I have not seen this outside of exam conditions, but then these exams are three hours long, and it is not every iPad, only about 5-10%. We are in the process of setting up an automated test rig using Amazon's iPad provisioning and an automated test framework. Its possible we could use this to look into this problem.

It is not clear if this is related to the keyboard problem.
