### ISSUE TITLE
How to add a Prohibited Process for Mac

### ISSUE THREAD

**Issue by Salveenee** [SafeExamBrowser/seb-mac#213]
Hi,
I'm having difficulties trying to block the use of AnyDesk with SEB (3.0) for OS X version.
Blocking it for Windows was easy; I just added AnyDesk.exe to prohibited processes and it worked.
But adding AnyDesk.app for osX version (as shown in the picture) didn't work and the AnyDesk connection continues after I launch SEB on a iMac with Big Sur.
 Can anyone help me?
![SEBnoAnyDesk](https://user-images.githubusercontent.com/106233526/170238953-06a84680-5b2c-4307-bf00-bc35277bf36e.jpg)

**Comment by danschlet** [comment]
You have to use the Mac version, as unfortunately the SEB Configuration Tool of SEB 3.x misses important settings (which SEB 2.4.1 still has). Mostly you need to enter the bundle identifier in the field "Identifier". You anyways need a Mac to find out the bundle ID. There's probably an easier way, but you can start AnyDesk, open the Activity Monitor app, find the AnyDesk process, double click for the process detail window, press the "Sample" button and in the Sample details you will see the "Identifier:" information. I don't have or know AnyDesk, if you could find out the bundle identifier, we can add it to the next SEB version as a preset default prohibited process.

**Comment by Salveenee** [comment]
> Mostly you need to enter

TY for your answer.
I'm not skilled with Mac and when I looked for SEB Configuration Tool of SEB 3.x I couldn't find it and I thought the Windows version was good for both.
Ok, I'll try to do as you wrote, but when you say to enter the bundle identifier, you mean AnyDesk, right?

**Comment by danschlet** [comment]
We need to add the missing "Indentifier" setting in the Windows Config Tool. The Windows tool contains all common settings and some of the Mac-specific ones, but some are included for now, as we're planing to refactor the configuration tool completely.

No, you need to add the string "com.philandro.anydesk" for the (in Windows 3.0 Config Tool missing) Identifier parameter and "AnyDesk" for Executable. Also you can select "Force quit". Probably you could use the Config Tool of SEB 2.4.1 if that's easier than using a Mac. Attached is a config file which contains that prohibited process (I also added it as a preset default to the upcoming 3.1 release). You could also use a text editor with an unencrypted config tool and copy paste these lines in the correct place (where the other prohibited processes are listed):

`		<dict>
			<key>active</key>
			<true/>
			<key>executable</key>
			<string>AnyDesk</string>
			<key>identifier</key>
			<string>com.philandro.anydesk</string>
			<key>ignoreInAAC</key>
			<true/>
			<key>os</key>
			<integer>0</integer>
			<key>strongKill</key>
			<true/>
		</dict>
`

**Comment by Salveenee** [comment]
Thank you again; i've been able to do it, using SEB confing tool 2.4.1.
Now I'll have to do the same for most used programs that works like TeamViewer and AnyDesk (but now I understand haw to find the bundle identifier on Mac, so no problem).

**Comment by danschlet** [comment]
Here you can see the list of programs which are by default blocked by SEB 3.0:
https://github.com/SafeExamBrowser/seb-mac/blob/3.0_unified/Classes/ConfigFiles/SEBPresetSettings.m
TeamViewer for example is already on that list, so you don't need to add it to your settings manually. 

This is the list for the upcoming SEB 3.1 release (now containing AnyDesk):
https://github.com/SafeExamBrowser/seb-mac/blob/1e4a8c398e8134abec2944e17d8f1e29f2e31722/Classes/ConfigFiles/SEBPresetSettings.m#L113

If you find more commonly used programs to want to block, let me know their bundle identifier and app name, then I could also add them to the next SEB update.

**Comment by Salveenee** [comment]
Another frequently used program of this kind, is chrome remote desktop that's a normal extension of Google Chrome.
So would be enought to block Chrome.

mac identifier: com.google.Chrome
app Chrome
pc: chrome.exe

**Comment by danschlet** [comment]
The preset default prohibited process should suffice:
                          @"executable" : @"Chromium Helper

This stops video conferencing and screen sharing, without having to quit the browser.
