### ISSUE TITLE
Text area in Quiz with Question Type Short answer not resizable on mac in Safe Exam Browser

### ISSUE THREAD

**Issue by Bindiya7567** [SafeExamBrowser/seb-mac#221]
When teachers create a Quiz with Question Type as Short Answer. The Text are in Answer Field is not resizable on Mac Device
![QUIZ_MAC_SEB](https://user-images.githubusercontent.com/51732779/175203176-0b3a0393-7a4d-4527-b747-b6b6292c3c40.jpg)
![Quiz_SEB](https://user-images.githubusercontent.com/51732779/175203280-b18158a6-515f-424d-a1ed-f1aed622b2aa.png)

**Comment by MichaelHeydon** [comment]
Hi @danschlet, set up SEB 3.1 for macOS to go to the `startURL`: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea 

The `<textarea>` on the right hand side is not resizable as expected as the resize handle does not appear to be visible. 
![screenshot-www w3schools com-2022 06 27-09_28_22](https://user-images.githubusercontent.com/74880856/175838011-fd0a80dd-094f-4189-8c4c-159398aa7163.png)

**Comment by danschlet** [comment]
Hi @MichaelHeydon 
It works with the modern WebView. When I use default SEB settings and just open that URL, the text area is resizable. 
The classic WebView is deprecated and lacks support for many modern web technologies/APIs. Therefore you must make sure that SEB settings for your system allow SEB to use the modern WebView. [See our explanation how to implement the SEB JavaScript API](https://safeexambrowser.org/developer/seb-config-key.html) to query the Config Key / Browser Exam Key hashes, as the modern WebView doesn't support sending it in custom HTTP request headers. The SEB Moodle integration has been updated for this, but it's still being integrated into one of the next minor Moodle updates.
