### ISSUE TITLE
Safe Exam Browser Quits Unexpectedly

### ISSUE THREAD

**Issue by vanie76** [SafeExamBrowser/seb-mac#227]
Hi 
My student received this message when she launch SEB on MAC M1
![image](https://user-images.githubusercontent.com/87995554/183355199-af6885f6-82cd-440c-befb-cd9186a9cdc9.png)

**Comment by vanie76** [comment]
Sorry for the inconvenienced caused
Any solution for this?

**Comment by danschlet** [comment]
No, this is not enough information to analyze the problem. The crash log shows that it is a crash of the WebKit web browser engine, which is generally not easy to track down. Check the support reporting instructions on our page https://safeexambrowser.org/support_en.html. In this case these are particularly important:

- Always try to reproduce a problem and if you can, post the exact steps to reproduce the problem. Usually it's only possible to solve problems which can be reproduced.
- Find out if the problem happens on other computers too. If it happens only on some computers and not on all, what do those have in common?
- Send us SEB log files (see here where to find them on [Windows](https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane)/[macOS](https://safeexambrowser.org/macosx/mac_usermanual_en.html#SecurityPane)) and mention the exact time when the problem happened (so we can find it in the log files).

**Comment by LorenzoC03** [comment]
I have a similar problem: SEB allow me to start a practice exam but after a while it crushes suddenly, not letting me finish the practice and it would be a problem when I’ll have to take the real exam. If you please could analyze if there are problems it would be helpful

**Comment by danschlet** [comment]
What we answer just above your post is still valid: We need the information stated there, otherwise we cannot find out what the reason for the problem is. In addition: What exam system are you using (Moodle, Inspera etc.)?
