### ISSUE TITLE
WiFi does not reconnect in AAC mode

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-mac#23]
We have seen several examples, during a long 3 hour exam, where the iPad has fallen off the Wifi, and does not auto-reconnect whilst in AAC mode. We have to exit AAC mode, go to settings, reselect the correct WiFi, wait for it to connect, and then re-enter AAC mode in SEB, then get the candidate to re-login to the exam to get the iPad back online. As our exam software supports offline use (single page app using IndexedDB), this does not disturb the candidate during the exam, but it creates work, and worry/stress for candidates and invigilators at the end of the exam. Is this a known issue?

**Comment by danschlet** [comment]
I'm sure that's a general WiFi issue and not related to AAC mode or SEB. WiFi stability is a regular issue and depends on many factors, probably network engineers should have a look at your infrastructure and WiFi access points/routers (also make sure they use current firmware).

What I will try is to integrate a WiFi widget to SEB for iOS similar to the Windows version, which would allow to reconnect to a network inside of SEB. There are some APIs in iOS which should allow this, but some require a private entitlement which Apple usually only grants to WiFi infrastructure developers, so I might have to negotiate with them.

**Comment by keean** [comment]
The question is why does it not auto-reconnect, why does it just sit there and not even try and reconnect?

**Comment by danschlet** [comment]
That's a good question, do you think the same devices would auto-reconnect in the same room when not running in the kiosk mode? If you're sure about that, then that might be an iOS bug which should be [reported to Apple](https://developer.apple.com/bug-reporting/).

**Comment by keean** [comment]
iOS 11 has a feature on phones where it stops trying to reconnect to poor WiFi. This could be related to that, or it could just be a red herring.

**Comment by seangirard** [comment]
Just coming to report an unrelated issue, but noticed this and thought I would comment that we experience this exact same issue as reported by @keean

**Comment by danschlet** [comment]
This is an iOS issue, please report the bug to Apple at: https://developer.apple.com/bug-reporting/
