### ISSUE TITLE
Automatically block other language keyboard inputs except for a chosen default

### ISSUE THREAD

**Issue by bradcarmichael1** [SafeExamBrowser/seb-mac#231]
Hi team, a bit of a strange one.

Would it be possible to add a feature to automatically block all other languages as a keyboard input except for a chosen default in SEB's settings?

EG: We have an English unit that is focused on teaching students simplified Chinese. If they have the Chinese Simplified language keyboard option installed in Mac OS and set as the keyboard input option, it will popup with suggested words which can potentially by used by students to easily answer quiz questions.

Ideally it would be good to be able to "lock" down only one usable keyboard option as set by the lecturer/teacher of the unit within the SEB configuration such as English in this scenario or whatever language is relevant to other localised use cases.

**Comment by danschlet** [comment]
I guess this applies only to Windows (I saw the other issue you opened)? The Mac version of SEB blocks the system's predictable text suggestions, although I never tested this with languages like Chinese. I just know that some system popup windows are blocked by SEB anyways (which can also be a problem if they are required). This may happen in the standard kiosk mode or only in the AAC single app assessment mode (see Preferences/[Security](https://safeexambrowser.org/macosx/mac_usermanual_en.html#SecurityPane)). So this may be a workaround for this use case.

At some point I will clarify if it's possible in the Mac version to allow only specific spell checking locales (which are coupled with the keyboard map usually), but this will have to wait for some future updates.
