### ISSUE TITLE
Iphone

### ISSUE THREAD

**Issue by Arliens** [SafeExamBrowser/seb-mac#233]
on my iphone I can't quit the session because I forgot the password I made myself, how do I fix it, thank you
![IMG_20220913_235652](https://user-images.githubusercontent.com/113457840/189949595-502ab023-e826-4d4e-8012-7bcb3f487215.jpg)

**Comment by danschlet** [comment]
You can force restart your iPhone: https://support.apple.com/guide/iphone/force-restart-iphone-iph8903c3ee6/ios
