### ISSUE TITLE
disservizio seb

### ISSUE THREAD

**Issue by leocarde** [SafeExamBrowser/seb-mac#234]
scrivo in merito ad una problematica riscontrata su SEB, nello specifico il browser non mi permette l’attivazione del microfono e della telecamera. 
Ho un mac del 2012 con istallato macOS 10.15.7
perche?

**Comment by danschlet** [comment]
Automatic translation:

> I am writing about a problem encountered on SEB, specifically the browser does not allow me to activate the microphone and the camera.
> 
> I have a 2012 mac with installed macOS 10.15.7
> 
> Why?

See our [download page description](https://safeexambrowser.org/download_en.html#MacOSX) and [release notes](https://safeexambrowser.org/macosx/mac_release_notes_en.html):

- Access to camera/microphone (getUserMedia Web API) via WebRTC available on macOS 11.1 Big Sur and newer.  

Apple added the necessary WebKit browser engine APIs only in macOS 11.1, so it's not possible to access the camera in the SEB browser with macOS 10.15.7.
