### ISSUE TITLE
SEB downloaded from english page still installs software in German

### ISSUE THREAD

**Issue by acamacho-unige** [SafeExamBrowser/seb-mac#237]
Hi guys,

We have a problem this year, that we never see before.
Usually - it seemed to us - what defines the language of Safe Exam Browser is the executable file that is downloaded from official website.

- When students downloaded the .dmg file from English page, software would be in english
- When students downloaded the .dmg file from German page, software would be in german

Weirdly, this year, students on MacOS all go to the english page, download the software and install it.
After that, SEB is in german and we can't find any way to change this.

Could it be possible that the .dmg file in english page is the wrong one (with german embedded) ?

Let us know if we are doing something wrong, or if the language switch method has changed.
Thank you very much.

**Comment by danschlet** [comment]
Your assumption is wrong, there is and always was only one version of SEB for macOS. The user interface language is selected (as in almost all Mac apps) according to the macOS account language/locale selected by the user. Therefore only when users use their Mac in German (macOS and other apps are using German language), SEB should be using German as its interface language.

Is this not the case? Are users with their macOS set to for example French having SEB using German? SEB for macOS no longer contains a French localization (we would need someone to contribute the very extensive translations), so it should automatically run in English, which is supposed to be the base language (used in all cases when the system language/locale isn't German). In case this happens with SEB 3.1, can you try it with SEB 3.0?

**Comment by danschlet** [comment]
I just tried to set my Mac (macOS Monterey 12.6) to Français (Suisse), and SEB 3.1 correctly runs in English.

On macOS there currently isn't a setting to change the app language manually (not using the macOS setting for language/locale, iOS has such a setting). I had a feature request to add this setting in SEB for macOS and I am considering this for the next major release. Currently, users with a German macOS setting would need to change this to English in System Preferences / Language & Region before starting SEB. They don't have to reboot their Mac and after their exam they can change it back to German.

**Comment by acamacho-unige** [comment]
Hi,

> I just tried to set my Mac (macOS Monterey 12.6) to Français (Suisse), and SEB 3.1 correctly runs in English.

Ok, weird. I had a Macbook Air M1, running Monterey too in english and Safe Exam Browser is displayed in German. I will try to test it downgrading SEB to 3.0.

> On macOS there currently isn't a setting to change the app language manually (not using the macOS setting for language/locale, iOS has such a setting). I had a feature request to add this setting in SEB for macOS and I am considering this for the next major release. Currently, users with a German macOS setting would need to change this to English in System Preferences / Language & Region before starting SEB. They don't have to reboot their Mac and after their exam they can change it back to German.

Oh all right, my mistake.

But I can confirm - as yesterday, we asked a few dozens students to install Safe Exam Browser on their computer, from oficial source - that all these students had NOT their computer in German (they had either French or English) and for **all of them** SEB seems to launch in german language.

Didn't really know what to tell them to change their SEB to english, as all them system was already in English or French, and no setting for that.

I will try with SEB 3.0, but I think there must be a small thing somewhere regarding our experience of the other day.

Thanks again !

**Comment by danschlet** [comment]
That sounds really weird. I'm using my Macs in English (but US English, not UK English), and never had SEB running in German. 

Could it be that you and your students use some third party tool which might have something to do with language selection or similar?

**Comment by acamacho-unige** [comment]
Mmmmh I don't think so.

And if students could have some weird configuration, I also used a UNIGE Macbook Air M1 test computer, which usually does not have any special configuration or setup.

And I saw the same result, downloaded and installed SEB, and boom ... it's in German, when all my system is not in German.

One thing is that this does not seem to reproduce on computers that had SEB installed, and that only replaced old SEB.app version with a new one. Don't know if it helps.

Would a video of that be usefull ?
Do you want some SEB logs from a machine that has this issue ?

**Comment by danschlet** [comment]
Yes, please send a video and log files from an affected machine.

Maybe Apple changed something in recent macOS versions. Do you know if it also happens on Macs with older macOS versions than Monterey?

**Comment by acamacho-unige** [comment]
> Maybe Apple changed something in recent macOS versions. Do you know if it also happens on Macs with older macOS versions than Monterey?

Yes, I think so, but I can check this out.

I'm gonna try to reproduce this problem on a < Monterrey MacOS computer, and will send (privately) logs and video as soon as I have them.

Thanks

**Comment by danschlet** [comment]
Bingo! Apple actually changed something, and apparently already in macOS Catalina (which I didn't know, my bad):
https://support.apple.com/guide/mac-help/change-language-region-apps-preferences-mac-mchlddb13d65/mac
https://beebom.com/how-customize-language-settings-specific-apps-macos-catalina/

So you can change language individually for each app, I assume on those Macs for unknown reason this is set to German for SEB. I don't have any idea why this happens automatically when installing SEB freshly, doesn't make any sense to me. But I will find it out...
