### ISSUE TITLE
Dateidownload bei webtigerjython funktioniert nicht (iOS)

### ISSUE THREAD

**Issue by TerraStudio** [SafeExamBrowser/seb-mac#238]
Hallo,

ich teste derzeit den SafeExamBrowser für eine Klausur an unserer Schule auf einem iPad aus.
Die Schüler müssen auf https://webtigerjython.ethz.ch/ Python Programme schreiben und am Ende herunterladen, um sie auf einer anderen Seite hochzuladen.

Die Seite bietet über das Menü oben Rechts eine Download Möglichkeit der Dateien an.
Leider führt dies beim SEB zu einem WhiteScreen und es ist danach auch nicht mehr möglich zurück zur Startseite zu gelangen oder die aktuelle Seite neuzuladen.

**Comment by danschlet** [comment]
Die iOS-Version unterstützt momentan keine Downloads, mit Ausnahme von Website-generierten Daten (mittels data: Schema, nicht blob:), welche von manchen Systemen bei Internetausfall erzeugt werden (als Backup für die Prüfungsdaten). Dies sind leider Einschränkungen der Browserengine, welche nicht so einfach zu umgehen sind. Wir werden uns das anschauen, sobald Zeit dafür ist.

**Comment by danschlet** [comment]
> und es ist danach auch nicht mehr möglich zurück zur Startseite zu gelangen oder die aktuelle Seite neuzuladen.

Wenn die [Navigation](https://safeexambrowser.org/macosx/mac_usermanual_en.html#BrowserPane) in den Einstellungen erlaubt ist (iOS Manual ist noch nicht aktualisiert, es gibt aber dieselben Einstellungen), kann man zurück navigieren, ausserdem kann man die [Back To Start](https://safeexambrowser.org/macosx/mac_usermanual_en.html#ExamPane) Funktion benutzen, wenn entsprechend konfiguriert. 

Falls es trotzdem nicht funktioniert, können Sie uns Ihre Einstellung senden, dann können wir uns das gerne genauer anschauen.

**Comment by TerraStudio** [comment]
Es geht trotzdem nicht. Wo soll ich die Datei hinsenden?

**Comment by danschlet** [comment]
Entweder hier als Attachement oder an info at safeexambrowser.org.

**Comment by danschlet** [comment]
Fixed in [SEB 3.2.1](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.2.1).
