### ISSUE TITLE
JavaScript calls in SEB on Mac do not return proper values for confirm dialog windows

### ISSUE THREAD

**Issue by pkarjala** [SafeExamBrowser/seb-mac#24]
OS:  macOS 10.13.6, also 10.11.6, Windows 10
SEB Version:  2.1.3 Mac, 2.2 Windows
jQuery 1.12.4

When a JavaScript [confirm dialog](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) is generated by a web page, it will give two options, "Cancel" or "OK".

If `Cancel` is clicked, the function returns `false`.
If `OK` is clicked, the function returns `true`.

I have a JavaScript `if` condition that checks on which button is clicked in a confirm call.  When using SEB on MacOS, if you click `cancel` then the confirm still returns `true`.

This is not normal JavaScript functionality, as the result should reflect which button is clicked as listed above.  This only occurs on the macOS SEB version 2.1.3, under both OSes tested above.  I have tested it under Safari 11.0, Firefox 56, and Chrome 61 on Mac OS 10.11.6. This does not occur on the SEB 2.2 version under Windows or any Windows browsers, which leads me to think it is an issue specific to the Mac version.

I have created a test page at https://kaiapuni-wp.coe.hawaii.edu/test.html that shows the problem.  The test code is as follows:

```
<!doctype html>
<html>
<head>
  <title>Testing JS</title>
  <script
  src="https://code.jquery.com/jquery-1.12.4.js"
  integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
  crossorigin="anonymous"></script>
</head>
<body>
  <h1>Testing <code>confirm();</code> functionality</h1>
  <p>
    <a href="https://kaiapuni-wp.coe.hawaii.edu/" id="test-link">Click to test jQuery calls</a>
  </p>
  <div>
    <strong>Result is:</strong> <span id="link_result_text"></span>
  </div>
  <h1>Test 2</h1>
  <p>
    <button onclick="buttonClicked();">Click to test vanilla JS calls</button>
  </p>
  <div>
    <strong>Result is:</strong> <span id="button_result_text"></span>
  </div>
</body>
  <script>
    // Tests the confirmation event using jQuery.
    var testConfirmation = function(event) {
      var span = document.getElementById( "link_result_text" );
      result = window.confirm( "Click OK to continue, cancel to stop!" );
      if ( result ) {
        span.textContent = "Clicked OK: " + JSON.stringify( result );
        console.log( "Clicked OK" );
        return true;
      } else {
        span.textContent = "Clicked Cancel: " + JSON.stringify( result );
        console.log( "Clicked Cancel" );
        event.preventDefault();
        return false;
      }
    }
    // Fire on-click function.
    $("#test-link").on("click", testConfirmation);

    // Tests confirmation event using vanilla JS.
    function buttonClicked() {
      var span2 = document.getElementById( "button_result_text" );
      result2 = window.confirm( "Button!  Click OK to continue, cancel to stop!" );
      if ( result2 ) {
        span2.textContent = "Clicked OK: " + JSON.stringify( result2 );
        console.log( "Clicked OK" );
      } else {
        span2.textContent = "Clicked Cancel: " + JSON.stringify( result2 );
        console.log( "Clicked Cancel" );
        return false;
      }
    }
  </script>
</html>
```

**Comment by danschlet** [comment]
Thank you for this really comprehensive and professional bug report. The Mac version apparently had this issue since the beginning. Looks like no one ever used a JavaScript confirm dialog with two buttons (OK/Cancel) or they didn't report the issue. I fixed the issue in the first preview build of SEB 2.1.4 (link to the testing repository see below). I don't have a final estimate when 2.1.4 will be released (ideally late summer or early fall, but can get delayed). If you urgently need the Cancel button in JavaScript confirm dialogs you can use this 2.1.4pre1 version though, because it just contains two small changes from 2.1.3 and it is a release build.

**To others reading this: This is how a issue report should look like, so that we can reproduce, debug and fix the issue efficiently. Please follow this lead!**

**Comment by pkarjala** [comment]
Thank you for the prompt response and fix!  We really like the functionality that SEB provides.

I have downloaded and verified SEB Mac 2.1.4 has fixed this issue.  We will not likely need to use the software before January 2018, but this will allow us to continue testing our exam system against SEB to see if any other issues crop up.

Marking resolved.
