### ISSUE TITLE
Disable Force Click (touch) when using SEB for MacOS

### ISSUE THREAD

**Issue by danschlet** [SafeExamBrowser/seb-mac#243]
### Discussed in https://github.com/SafeExamBrowser/seb-mac/discussions/242

<div type='discussions-op-text'>

<sup>Originally posted by **pberndt12** November  8, 2022</sup>
Is there a way to disable Force Click (touch) in SEB to keep students from highlighting a word and force clicking it to bring up the dictionary?</div>

**Comment by danschlet** [comment]
When Look up & data detectors is set to "Force Click with one finger" in System Preferences / Trackpad / Point & Click, then look up using a trackpad force click on words on web pages works in the modern WebView. If your web application works with the classic WebView, you can use the setting in SEB Preferences / Browser / Select Browser Engine Policy : Force classic as a workaround. We'll try to fix this in the next update.

**Comment by NullifiedJosh** [comment]
This can be dissabled in the config?

**Comment by danschlet** [comment]
Fixed in [SEB 3.2.1](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.2.1).
