### ISSUE TITLE
Zoom SDK Update Needed (also in 3.2rc please?)

### ISSUE THREAD

**Issue by blanderson22** [SafeExamBrowser/seb-mac#250]
In SafeExamBrowser for MacOS we're seeing a message about the need to update the Zoom SDK. 

Our students using Macs are currently using SEB for MacOS version **3.2rc** so they are able to connect to our SEB Server with Zoom proctoring integration. 

Is there a possibility that the Zoom SDK can also be upgraded in 3.2rc, pretty please?

**Comment by danschlet** [comment]
We will update the Zoom SDK.

Please note that we might no longer be able to publicly distribute a Safe Exam Browser version containing the Zoom SDK integration due to licensing reasons. We may provide such a version only to SEB Alliance contributors which then would need to make sure to distribute that version only to their employees, students, customers or similar. We are currently clarifying the exact conditions how we can distribute an SEB version with integrated Zoom SDK.

**Comment by blanderson22** [comment]
That is interesting regarding the licensing. Since we're required to include our SDK key/secret in the setup of the meeting one would think that the licensing and authentication would be verified in that exchange. 

Is there a modification or workaround I can make so we can proctor our exams in the meantime?

**Comment by blanderson22** [comment]
Hi, I was checking to see if there's a beta release, or otherwise, of SEB for MacOS 3.2rc available with the updated Zoom SDK? The developer of the windows version had provided a link to a beta release containing the updated Zoom SDK, so I was hoping to get the same for MacOS. We work in a BYOD environment so we have a mix of windows and mac.

**Comment by danschlet** [comment]
The upcoming public release of SEB 3.2.1 for macOS won't contain Zoom proctoring anymore for above mentioned legal reasons. We will update the Zoom SDK in the non-publicly available version SEB 3.2.1 Alliance Edition after the public release of 3.2.1 (likely in the next couple of weeks). If you like access to such a version supporting Zoom proctoring, you may discuss this with the SEB Alliance manager Thomas Piendl, alliance @ safeexambrowser.org.

**Comment by blanderson22** [comment]
Based on your previous comments I thought that was still being considered, especially given that SDK credentials are required to authenticate the Zoom license. 

Why does the treatment of the Zoom SDK differ in the macos version versus the windows version?

**Comment by danschlet** [comment]
For technical/legal reasons. The public SEB version for Windows uses the Zoom Web API to connect to the Zoom service, the macOS version contains the native Zoom SDK. The native SDK are actual source and binary code distributed by Zoom using a proprietary license. Unfortunately despite we were trying for months to get a permission to distribute an SEB version containing the Zoom SDK, Zoom wasn't able to clearly answer our questions (see https://devforum.zoom.us/t/use-meeting-sdk-in-an-open-source-freeware-educational-app/66305).
