### ISSUE TITLE
Unable to preview Chinese popup keyboard for MacOS

### ISSUE THREAD

**Issue by jonnypui** [SafeExamBrowser/seb-mac#251]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
I am working on creating an SEB configuration file for students with the Chinese keyboard language installed on Windows & MacOS. I have recently discovered that disabling Kiosk Mode (None for debugging only) or setting Kiosk to "Create New Desktop" would allow Windows users to still see the Chinese pop up keyboard during SEB tests. However, this did not fix the popup keyboard appearing in MacOS devices. I've tested many different settings with SEB Configuration tool in both Windows & Mac but was unable to find any solution. 

**Screenshots**
CN popup keyboard appearing on Windows
![CN popup keyboard appearing on Windows](https://user-images.githubusercontent.com/43037228/203126076-afa881b6-1744-4d49-92dd-6339ca9ade7c.png)

Screenshot of Chinese popup keyboard not appearing in MacOS 
![CN popup keyboard not appearing on MacOS](https://user-images.githubusercontent.com/43037228/203127512-75057d66-eb62-4866-b552-50cfe9928a55.png)

**Version Information**
 - OS: Tested on Windows 11 Version 22H2
 - OS: Tested on MacOS Monterey Version 12.5.1
 - SEB-Version [SEB 3.3.2] (Windows machine)
 - SEB-Version [SEB 3.0 (343F)] (Mac machine)

**Comment by jonnypui** [comment]
Just wanted to give this a bump to see if any progress has been made.
Thanks.

**Comment by jonnypui** [comment]
Bump!

**Comment by danschlet** [comment]
No answer means no progress…

No, sorry, but we’re terribly busy with working on other issue fixes and feature requests from stakeholders (internal and SEB Alliance contributors). Unfortunately we have to prioritize. I don’t think there is an easy solution for the issue, likely only Apple can fix it for Assessment Mode (AAC kiosk mode). I mentioned the issue to them, latest just yesterday and I will create a feedback (bug report) next week, which they promised me to prioritize. 

I’ll also have a deeper look at it once again, but that I can only do after the 3.3 release (probably later in April).

**Comment by danschlet** [comment]
PS: If my initial analysis is correct, that there’s no easy solution without Apple fixing it, this will only happen in future macOS releases. Did you investigate if there is some browser based (plugin) or web application framework which could be used as a workaround?

**Comment by danschlet** [comment]
Ok, I tried it now again on macOS 12.6.4 with the AAC kiosk mode (see Preferences / [Security](https://safeexambrowser.org/macosx/mac_usermanual_en.html#SecurityPane) / Use Assessment Mode (AAC) if available) and it works (at least if I had the correct Chinese popup keyboard activated)! I guess Apple actually fixed it (I'm quite sure it didn't work in some of the first versions of the AAC mode).  

AAC Mode has some restrictions and it only works without having to add all domains which your assessment solution uses to SEB settings (see [release notes](https://safeexambrowser.org/macosx/mac_release_notes_en.html) for SEB 3.1.1) if you're using macOS 12.1 or newer. 

The other option is to disable the SEB kiosk mode completely (disable "Use Assessment Mode (AAC) if available" and enable Preferences / Applications / [Permitted Processes](Use Assessment Mode (AAC) if available) / Allow switching to third party applications. But I don't see the point using SEB if you have to disable the kiosk mode (which is also true for the Windows version).

**Comment by jonnypui** [comment]
That's amazing to hear. I will perform testing on Monday! Thank you for your quick response!

**Comment by jonnypui** [comment]
Brilliant! Works perfectly fine with Assessment mode turned on (From MacOS side SEB Configuration). Might be useful to also note, I got it working for Windows after enabling "Show Keyboard" option too.
