### ISSUE TITLE
CSS rotate and width do not render correctly in SEB on macOS

### ISSUE THREAD

**Issue by solliegarcia** [SafeExamBrowser/seb-mac#26]
OS: macOS 10.10.5, Windows 10
SEB Version: 2.1.3 Mac, 2.1.4(pre2) Mac, 2.2 Windows

When using the CSS property `width`, setting a parent div to `width` of 100% and having two child divs set to a `width` of 50% causes the macOS version of SEB to not correctly render. I have had this occurrence in SEB version 2.1.3 and 2.1.4(pre2) on macOS. I have tested it under Firefox 62, Chrome 69, and Safari 10 on macOS and it is rendering correctly. It's also been tested on SEB version 2.2 on Windows which functioned normally. 

`rotate` does not render. This was also tested on all the platforms listed above and only occurred on the macOS versions of SEB. 

Here is a screenshot of a test done in Safari 10 on macOS.

![screen shot 2018-09-14 at 3 13 07 pm](https://user-images.githubusercontent.com/22554003/45580778-bc2ff280-b830-11e8-8e6e-c053996226fa.png)

And here is the same page in SEB version 2.1.4(pre2).
_sorry for the low-quality picture of a screen_

![img_3822](https://user-images.githubusercontent.com/22554003/45580696-db7a5000-b82f-11e8-8a44-d40dde117397.jpg)

```html
<!doctype html>
<html>
<head>
  <title>CSS Width and Rotate Test</title>
  <meta charset="utf-8"/>
  <style>
    .matchable-area, .parent-div {
      display: flex;
      width: 100%;
      margin-bottom: 5px;
    }
    .cell-option, .cell-slot {
      display: flex;
      width: 50%;
      position: relative;
      vertical-align: top;
      padding: 10px 16px;
      border: 2px solid black;
    }

    .test-rotate {
      transform: rotate(45deg);  
      position: absolute;
      margin-top: 10px;
      padding: 5px;
      border: 5px solid black;
    }
  </style>
</head>
<body>
  <h1>Testing CSS <code>width</code> and <code>rotate</code></h1>
  <h2>Testing <code>width</code></h2>
    <div class='parent-div'>
      <span class='cell-option'>width: 50%</span>
      <span class='cell-slot'>width: 50%</span>
    </div>
  <h2>Testing <code>rotate</code></h2>
  <div class="test-rotate">rotate</div>
</body>
</html>
```

**Comment by danschlet** [comment]
I guess this is an issue of specific WebKit versions. Maybe it is/will work correctly on newer macOS versions or when we transition to WKWebView (WebKit 2). Anyways, we can't fix bugs in the browser engine, if it doesn't work with current WebKit versions, then you have to file a bug report at webkit.org.
