### ISSUE TITLE
Errors when loading page in mac SEB

### ISSUE THREAD

**Issue by Sven-Callewaert** [SafeExamBrowser/seb-mac#262]
Issue occurs on SEB 3.1 and 3.2.1 on macOS 12.4.

We're using SEB to launch online exams using the assessmentq platform. This works fine in Windows and also worked ok on macOS with SEB < 3.0. When the exam is launched with SEB on macOS we're getting:

> Exception: TypeError: null is not an object (evaluating 'document.querySelector('[href="about:blank"]').download')

The issue is possibly related to https://github.com/SafeExamBrowser/seb-mac/issues/220, but the page we're trying to launch does not use any iframes .

The error seems to happen on line 797 of SEBAbstractModernWebView.swift. When allowDownloads is false (by disabling downloads in the SEB config) the error is also gone, but the our application needs uploading and downloading. Would it be possible to add a null reference check?

**Comment by Sven-Callewaert** [comment]
This can be done by adding a question mark after the querySelector function, so line 797 becomes:
_webView.evaluateJavaScript("document.querySelector('[href=\"" + url.absoluteString + "\"]')?.download") {(result, error) in_

**Comment by danschlet** [comment]
Thank you, that is therefore similar like in Swift (I'm really not a JS developer...). I added this null reference check in SEB 3.2.2, but didn't had a test case. Hope it works now, would be great if you can confirm that.

**Comment by Sven-Callewaert** [comment]
I've checked it with SEB 3.2.2 on macOS and the exception is gone.
Thank you for the quick fix.
