### ISSUE TITLE
Possible way to cheat

### ISSUE THREAD

**Issue by ibi13** [SafeExamBrowser/seb-mac#263]
Hi,

Unfortunately I can't provide the version on which the issue occurs as I'm not the one that discovered it. I'm guessing it would be one of the latest mac/iOS versions as our class only installed the program last week.

There seems to be a way you can see your own images while using SEB:
When you open the chat with your teacher on a iOS device, you can attach files to your message. Thus you are able to see the photos saved on your own device before sending them. On Windows OS that doesn't work.

-J

**Comment by danschlet** [comment]
Btw. there is a setting in the Downloads tab "Allow downloading" which should in the modern WebView also disable uploads (in the classic WebView on iOS uploading was not possible at all). We will test this and update the UI text eventually to also cover uploads. Probably a separate setting for downloads and uploads would be even better.

Thanks for reporting this issue!

**Comment by danschlet** [comment]
This was fixed in SEB 3.3.2.
