### ISSUE TITLE
Third-Party Applications

### ISSUE THREAD

**Issue by ndum** [SafeExamBrowser/seb-mac#28]
Hello, are there any plans in SEB for Mac to run Third-Party Applications like on Windows without the parental control solution? Because for unmanaged devices the parental control solution is hardly applicable. Or is there another solution?

Thank you for the information.

**Comment by ndum** [comment]
Okay, thanks for the information. We will also try it with VMware Horizon HTML Access.

**Comment by danschlet** [comment]
Available as of SEB 3.4 for macOS.
