### ISSUE TITLE
MAC is pasting active url links to essee answer

### ISSUE THREAD

**Issue by UEF-SEB** [SafeExamBrowser/seb-mac#285]
Hi,
I´m not sure if this is SEB issue or MAC issue, but asking anyway if you have any solution to this. 
We are using SEB 3.4.1 for windows and SEB 3.2.3 for MacOS
Moodle is 3.10.
When there is a essay question in exam and students are allowed to use some web site to search information and paste that web site url to essay question as an answer "from what web site did you find that answer", then
- SEB 3.4.1 for windows: when the student pastes the url address, it comes as text
- SEB 3.2.3 for MacOS: when the student pastes the url address, it comes as a active link
-> If the student accidentally clicks that link, the page opens in the same window and the student cannot get back to the exam other than by closing the entire browser and starting over.

Is there anyway to get back in the exam page or de-activate the attached link

**Comment by danschlet** [comment]
It's a macOS feature that the contents of the clipboard are context-sensitive and not just plain text. Depending on the paste target, the content is either used as plain text or as the original content type of the clipboard, which in this case is a URL (link). Usually by using the shortcut shift-option-command-V, the content is pasted as plain text (works for example in the Notes app).

The rich text editor in Moodle is also accepting URLs as content as it seems. You could configure it to accept only plain text and no richt text or no HTML in your Moodle settings (check documentation, I just know that it's possible somehow).

**Comment by UEF-SEB** [comment]
Thank you, we just came to the same conclusion, that by changing the essay question to plain text type, this problem will be solved :)

**Comment by danschlet** [comment]
PS: You can configure back/forward navigation in SEB, see the [Browser](https://safeexambrowser.org/macosx/mac_usermanual_en.html#BrowserPane) and [User Interface](https://safeexambrowser.org/macosx/mac_usermanual_en.html#AppearancePane) panes in its Preferences. If navigation is not disabled, but you don't have the browser window toolbar enabled (no navigation buttons visible), you can use the standard navigation buttons cmd-Cursor left/right.

You can also activate the Back to Start button so students always can return to the Start URL or another configured URL.
