### ISSUE TITLE
Inspector element tool on mcbook pro

### ISSUE THREAD

**Issue by FoxDrill** [SafeExamBrowser/seb-mac#291]
On MacBook Pro, since version 3.0 of SEB, when activating the element inspector, the window of this tool flashes.

**Comment by danschlet** [comment]
Web Inspector doesn't work with the modern WebView (WKWebView). Please file a feedback (bug report/feature request) to Apple. I hope they will some day support it in WKWebView as well (it currently only works in the classic WebView).
