### ISSUE TITLE
Safe exam browser wont load extra website when clicking on it

### ISSUE THREAD

**Issue by lifeunexpected** [SafeExamBrowser/seb-mac#296]
We are having an issue that when you try to click a link marked in red that opens a new website nothing happens.
It has happened on macOS, SEB 2.1.4 or 2.3.2 

We tried logging out and back in again, re-started the mac but the same problem happens.

![image](https://user-images.githubusercontent.com/36742392/231419335-a7f32f11-3bfa-4e1e-b793-e7033f0acf69.png)

**Comment by danschlet** [comment]
This is fixed in SEB 3.2.x. Please note that Inspera according to my information will be supporting SEB 3.2.5 as of their after Easter update (so in the coming days?).
