### ISSUE TITLE
Mac Bloqueada

### ISSUE THREAD

**Issue by itzelmor** [SafeExamBrowser/seb-mac#298]
Buen día, el viernes por la tarde, accidentalmente abrí la aplicación de SEB EXAM BROWSER, h al momento de intentar salir de la aplicación me solicita una contraseña que no tengo, por lo que desde el viernes no he podido usar mi MacBook Air, me gustaría me ayudaran a solucionar mi problema.

**Comment by danschlet** [comment]
To unblock a Mac when you don't know the SEB quit password, you can force restart/shut down and start again. You might need to use Safe Boot because SEB may be started automatically. See our [FAQ](https://safeexambrowser.org/faq/faq_en.html#MacOSX).
