### ISSUE TITLE
EXC_BAD_ACCESS (SIGSEGV)

### ISSUE THREAD

**Issue by mesnmesn** [SafeExamBrowser/seb-mac#3]
We have a student using SEB 2.1.2 on Mac OS X 10.9.5, and the system crashed several times using SEB. SEB was successfully downloaded, but after opening a config file for starting an exam with the settings password, the system crashed. Here is the first part of the report. Can you help?

Process:         Safe Exam Browser [323]
Path:            /Applications/Safe Exam Browser.app/Contents/MacOS/Safe Exam Browser
Identifier:      org.safeexambrowser.Safe-Exam-Browser
Version:         2.1.2 (27A8)
Code Type:       X86-64 (Native)
Parent Process:  launchd [187]
Responsible:     Safe Exam Browser [323]
User ID:         501

Date/Time:       2016-12-16 11:21:09.547 +0100
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  1124ABF0-0F76-A232-BA3B-EF934AA184E3

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_PROTECTION_FAILURE at 0x00007fff52de4e48

VM Regions Near 0x7fff52de4e48:
    MALLOC_TINY            00007fec84700000-00007fec84e00000 [ 7168K] rw-/rwx SM=PRV  
--> STACK GUARD            00007fff4f5e5000-00007fff52de5000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                  00007fff52de5000-00007fff535e5000 [ 8192K] rw-/rwx SM=COW  thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libunwind.dylib                      0x00007fff8f6a7b51 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister(bool) + 33
1   libunwind.dylib                      0x00007fff8f6a7b26 unw_init_local + 138
2   libunwind.dylib                      0x00007fff8f6a8560 unwind_phase2 + 44
3   libunwind.dylib                      0x00007fff8f6a7a44 _Unwind_RaiseException + 248
4   libc++abi.dylib                      0x00007fff93033c4a __cxa_throw + 107
5   libFontParser.dylib                  0x00007fff89bb492d TcmapUnicodeTable::GetUnicodeSubtable(unsigned int&) + 335
6   libFontParser.dylib                  0x00007fff89b80051 TcmapUnicodeTable::TcmapUnicodeTable(TSFNTFont const&) + 79
7   libFontParser.dylib                  0x00007fff89b7fef5 TSFNTFont::GetGlyphsPerCharacters(unsigned short const*, unsigned short*, unsigned int&, bool) const + 55
8   libFontParser.dylib                  0x00007fff89b91ccc FPFontGetGlyphsForUnichars + 608
9   com.apple.CoreText                   0x00007fff8c0ecc0a TcmapTable::Map(unsigned short const*, unsigned short*, long&) const + 210
10  com.apple.CoreText                   0x00007fff8c0ecab2 TBaseFont::GetGlyphsForCharacters(unsigned short const*, unsigned short*, long) const + 82

**Comment by mesnmesn** [comment]
In the meantime, we have had two more students with the exact same problem according to the records - and using Mac OS X 10.9.5, too. The problem was solved by updating to a newer Mac version. 
Best,
Lisa

**Comment by danschlet** [comment]
I wonder if the crash happened when SEB already started loading the web page (exam) set as Start URL in those settings. The crash report indicates that it might be a problem with fonts. There is a known issue that websites using custom fonts might cause the system's WebKit browser engine to crash (leading to SEB crashing too). If the web page with those custom fonts is first loaded with Safari, those fonts are correctly loaded and thereafter also SEB can load that page.
