### ISSUE TITLE
RSOD / How to proceed

### ISSUE THREAD

**Issue by ohlma** [SafeExamBrowser/seb-mac#303]
Dear everybody,
after having used SEB for quite a time, suddenly some problems have appeared. I am posting this here because of the picture showing a Mac-screen. However, the problem occurred with various computers. People opened a file and some got locked in a red screen. This not being an unusual problem, my colleagues tried to unlock the notebooks by entering the password. This did not function (afterwards, they tried to enter all past passwords, none would work). 

So, the next step was - for all of the colleagues - to shutdown the computer and restart it. It still would not work, even safe mode could not be started. 

Is this a problem only some of our students had (while with others it was working perfectly)? Thank you so much for your answer.

Kind regards,
Manu

![MicrosoftTeams-image (6)](https://github.com/SafeExamBrowser/seb-mac/assets/133880458/243378ad-2704-4af6-865e-910fe53078b9)

**Comment by danschlet** [comment]
We don't have other reports of this problem. 

It's not easy to understand what went wrong here. SEB saves the start URL of a running secure session (quit password set) and removes this, when the session is ended (using a quit link or the quit button/key shortcut). If the session is not properly quit, then next time a secure session with the same start URL is started, this lock screen is displayed and can only be closed by **entering the current quit password of this new session** (NOT the quit password of the old session, that one is not saved by SEB). So they probably don't know the quit password of the new settings they started SEB with.

Note that this system may be confusing if you use client settings with a quit password set. We recommend to start exam sessions only with SEB configuration files [saved with the option](https://safeexambrowser.org/macosx/mac_usermanual_en.html#ConfigFilePane) "for starting an exam".

**Don't use SEB configuration files saved with the option "for configuring a client" and with a quit password set on BYOD student machines, only on institution owned, managed devices.** We will update the SEB manual for making this clearer (although I don't know if this is causing your issue).

> It still would not work, even safe mode could not be started.

I can't figure out that safe mode could not be started, I guess they didn't follow Apple's instructions properly, see here: [Safe Mode](https://support.apple.com/en-us/HT201262). Make sure to use the correct steps for their type of Mac (Apple Silicon M1/M2 etc. or Intel CPU).

After booting in safe mode, start Terminal and use the command to reset SEB settings:
`defaults delete org.safeexambrowser.SafeExamBrowser ` as [mentioned in our FAQ](https://safeexambrowser.org/faq/faq_en.html#MacOSX).

If they are still experiencing these red screens, ask them to film the screen to show what they do when this issue happens and they should send SEB log files from this location:
The log is saved to the directory ~/Library/Logs/Safe Exam Browser/ which is also displayed in the Console app log list.

**Comment by danschlet** [comment]
PS: Make sure to use the latest SEB version (currently 3.2.5). Do you know which version was used by those students? It's possible that there was a bug in a previous version which would have caused the running secure session not being reset correctly in some cases and then this red lock screen being displayed when the same start URL is used in settings. But still the current quit password should unlock SEB. If they were using an older SEB version and experienced this issue, it might help to reset SEB settings with the mentioned command `defaults delete org.safeexambrowser.SafeExamBrowser`.

**Comment by danschlet** [comment]
The new [beta version of SEB 3.3](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.3b1) implements an improved check for interrupted, not correctly finished sessions. Now unfinished sessions are only locked, if the new session uses the exact same settings (for example using the same quit password). This should avoid issues if an institution uses the same Start URL for a later exam.
