### ISSUE TITLE
Should I allow SEB to "control my computer"?

### ISSUE THREAD

**Issue by Krisell** [SafeExamBrowser/seb-mac#31]
I noticed the following settings in "Security and integrity" -> "Integrity" -> "Accessibility".
I'm not sure of the exact translation, but it basically asks "Allow the applications below to control your computer".

Should SEB be allowed? If so, what happens if this is not checked (I have not noticed any problems having it un-checked).

![image](https://user-images.githubusercontent.com/25909128/48352445-fa109200-e68c-11e8-8856-25a9014fd0cd.png)

**Comment by danschlet** [comment]
macOS 10.14 Mojave automatically displays this dialog when an application tries uses some code to access keyboard taps and mouse clicks. SEB for macOS does this only for specific cases, this warning might actually have been triggered by some outdated code, I'm currently checking this. If it still will be necessary then I will add information for what this is necessary.

In general this should not be considered a privacy issue, as SEB can only access the keyboard and mouse while running. On Macs, SEB never runs in the background (and definitely can't do that, as no administrator password needs to be entered when running SEB the first time and there is no installer).
