### ISSUE TITLE
White Screen / Black Screen nach Netzwerkunterbruch (OLAT)

### ISSUE THREAD

**Issue by micimh** [SafeExamBrowser/seb-mac#318]
Im vergangenen Semester hatten wir eine verhältnismässig grosse Anzahl von Prüfungsteilnehmenden, die bei der Verwendung von SEB während der Prüfung plötzlich einen weissen und/oder schwarzen Screen hatten. Das SEB-Fenster (also quasi der Rahmen mit den Buttons – Ausschalten, Reload, Back-To-Start etc.) war noch vorhanden, aber es wurde keine Inhalt der Website angezeigt, sondern eben nur ein weisser oder schwarzer Screen (siehe Anhang)

- das Problem ist in diesem Semester zum ersten Mal wissentlich aufgetreten; nicht zu 100% erwiesen, aber wir gehen davon aus, dass es sowohl mit Mac als auch mit Windows auftritt
- Issue tritt höchstwahrscheinlich ausgelöst durch einen Netzwerkunterbruch auf: Issue kann (mit Mac) einfach reproduziert werden -> Prüfung starten, WLAN ausschalten, ein paar Sekunden warten (schwarzer Screen), Klick auf SEB-Logo (weisser Screen)
- beim Wiedereinschalten des WLANs kommt die OLAT-Seite nicht zurück -> SEB muss beendet und neu gestartet werden
- offenbar tritt das Problem nur im Zusammenhang mit dem Baustein Test in OLAT auf (in anderen Situationen erhalte ich eine erklärende Fehlermeldung - siehe weitere Screenshots «NoNetw_Loginpage» / «NoNetw_Ordner»)

**Comment by micimh** [comment]
![White_Screen](https://github.com/SafeExamBrowser/seb-mac/assets/141831804/563061ff-52a6-4947-8cea-321b1f408e86)
![Black_Screen](https://github.com/SafeExamBrowser/seb-mac/assets/141831804/2d453ad2-9c10-4713-ae68-f0e66cf8157e)
![NoNetw_Ordner](https://github.com/SafeExamBrowser/seb-mac/assets/141831804/32f74e61-5193-4136-bf40-2517f59a846e)
![NoNetw_Loginpage](https://github.com/SafeExamBrowser/seb-mac/assets/141831804/e831bb7c-22ae-46f8-91ef-e722a8cd93a7)

**Comment by danschlet** [comment]
Der Grund für den schwarzen Bildschirm ist, dass das Browser-Fenster geschlossen wird durch die Web-Applikation.
Dies geschieht, nachdem ein Fehler beim Laden einer Inline-(Seiten-)Ressource gemeldet wird. Solche Fehler werden von SEB nicht angezeigt (nur wenn eine komplette Seite nicht geladen werden kann), was aber auch bei anderen Browsern der Fall zu sein scheint (zumindest auf der Startseite der Prüfung, wo angezeigt wird, dass nicht SEB benutzt wird, wenn ich die in Safari lade erscheint ebenfalls keine Fehlermeldung, wenn ich die Netzwerkverbindung trenne).

Warum aber dann OpenOlat versucht, das Browserfenster zu schliessen, verstehe ich auch nicht. Vielleicht ist das ein Feature der SEB-Integration in OpenOlat, wenn erkannt wurde, dass kein SEB-Browser verwendet wird? Das Browserfenster verschwindet ja auch erst einige Sekunden nach dem Trennen der Netzwerkverbindung.

Ich werde auf jeden Fall eine Änderung einbauen: In SEB sollte eine Web-Applikation das Haupt-Fenster (in der die StartURL geladen wurde) nie schliessen dürfen, da SEB einen Unterschied macht zwischen dem Prüfungsfenster und allen anderen, zusätzlich geöffneten Browserfenstern (man kann diese zwei Browserfenstertypen ja unterschiedlich konfigurieren). SEB wird also in diesem Fall den Befehl, das Haupt-Browserfenster zu schliessen, ignorieren. Dann sollte das Problem mit dem schwarzen Bildschirm nicht mehr auftauchen.

**Comment by micimh** [comment]
Lieber Daniel, vielen Dank für die schnelle Rückmeldung! Mit welcher Version würde diese Änderung kommen?

**Comment by danschlet** [comment]
Version 3.3. Ich habe jetzt eine [Release Candidate Version](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.3rc) veröffentlicht, wo dieses Problem behoben ist. Ebenfalls werden jetzt bis zu 20 Log-Dateien behalten (max. 20 MB).
