### ISSUE TITLE
Library 'SEBSupport' not found

### ISSUE THREAD

**Issue by chrisaut** [SafeExamBrowser/seb-mac#325]
Hi guys,

I'm trying to build the project using X-Code (15) and getting the following error:
```
ld: warning: search path '/Users/chris/dev/seb-mac/Frameworks' not found
ld: library 'SEBSupport' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Could you point me in the right direction where to get this framework?
FYI I tried building a few weeks ago already with version tagged as 3.2.4 but also couldn't get this to work as I got a different error, but I cannot even find which commit added this or where it is referenced and obviously would like to work on the latest version.

I do apologise but I'm very new to X-Code and MacOS dev in general so it might just be something stupid on my end.
Thank you in advance

**Comment by danschlet** [comment]
You have to remove the reference to this library from the project, as this is the binary security module which is not available as open source code.

**Comment by danschlet** [comment]
You can contact us at info at safeexambrowser dot org for information about this issue (please mention for what institution/company you're working and what the purpose is to build SEB yourself).
