### ISSUE TITLE
SEB not working on iOS 17 when Guided Access is enabled

### ISSUE THREAD

**Issue by PhilMan1234** [SafeExamBrowser/seb-mac#328]
SEB not working on iOS 17 when Guided Access is enabled. Before even starting the exam, this is what happens
![66af591f-f4f4-48fa-8804-2ebd99193d45](https://github.com/SafeExamBrowser/seb-mac/assets/148380909/9d636e38-2bc4-448b-9787-6982ca6dfb17)
![89dad6b6-bbd7-4646-b269-185144e138d4](https://github.com/SafeExamBrowser/seb-mac/assets/148380909/00f42645-9282-42ed-bbf2-113aa5bf5bbb)

**Comment by PhilMan1234** [comment]
The proposed solution in issue 321 does not solve the problem

**Comment by danschlet** [comment]
Did you read the whole discussion? It's a bug in iOS 17 and fixed in iOS 17.1 beta 3.
