### ISSUE TITLE
Media keys remap allows students to open Spotify

### ISSUE THREAD

**Issue by danielx** [SafeExamBrowser/seb-mac#33]
Hi,

We've gotten some reports that students while in SEB-mac 2.1.3 can press the play/pause button to open the Spotify player.

I've yet to get the full details of how the students remapped the key and if they can actually tab to Spotify but i'm guessing they are using an app such as this one: https://github.com/milgra/macmediakeyforwarder

Would something like this be possible to block since i'm guessing it might still work even if it is remapped to another app than Spotify? Perhaps we haven't set up our SEB config correctly to prevent this?

**Comment by danschlet** [comment]
Unfortunately macOS doesn't have an API to prevent applications running in fullscreen (on a separate space) to switch the space, the only way SEB can stop this is to force terminate such applications. This is currently being done with iTunes, but doesn't work if the media key is remapped to another application. Looks like we have to extend the feature to all possible applications (which was anyways planed). We will prioritize this now, thanks for reporting it.

**Comment by danielx** [comment]
Hi,

I've gotten some more details and it seems that in this case it was that the student could only control Spotify if they already had it open when starting SEB but can't switch to the Spotify-window.

It seems they haven't installed a custom app such as macmediakeyforwarder since Spotify just needs to be opened to respond to media key presses.

**Comment by danschlet** [comment]
The previously implemented fix for the issue that pressing the media play button could start a media player app and switch to its space (if that app was set to full screen before beforehand) is again working on macOS Mojave in the current [preview build 3 of SEB 2.1.4](https://github.com/SafeExamBrowser/seb-testing/tree/master/mac/2.1.4). 

SEB isn't blocking applications from playing audio by pressing the play button though. This won't be solved in 2.1.4 yet.
