### ISSUE TITLE
Touchbar re-programmable with software and not blocked by SEB

### ISSUE THREAD

**Issue by lifeunexpected** [SafeExamBrowser/seb-mac#34]
You can re-program the touchbar with apps to give you custom icons, text etc on the touchbar and this gives you the possibility to unwanted help.

Added some pictures regarding how this work and looks like.
You can add sub "folders" to each picture/button/text so this gives you the possiblity to have cheats per chapter of a book etc.

You need to run the software before you start SEB and to make it less visible or standing out you can take a default icon that might be normal to have there and hide your custom menu under it. 
Maybe even make it that multiple keys needs to be pressed for the sub cheat menus to show up.

https://ibb.co/wc6r9t2
https://ibb.co/YdV961y
https://ibb.co/Ct8QQ69
https://ibb.co/gR8rX3g

**Comment by danschlet** [comment]
Thanks for your report!

To disable all non-standard Touch Bar configuration automatically is planed for SEB 2.1.4 for macOS. Currently we were recommending institutions to instruct their invigilators to either enforce standard Touch Bar settings to be activated in System Preferences before starting SEB or to look out for students which do unusual things on their screens (which of course isn't so easy depending how good the "cheat trick" is. Also some exam systems detect if text is pasted into text fields instead of typed.

SEB 2.1.3 at least is blocking Touch Bar typing suggestions (predictive keyboard) during an exam. We don't recommend to use older SEB versions and we started to remove all older versions to motivate institutions to do more regular updates (but some just don't seem to care...).

**Comment by lifeunexpected** [comment]
Do you have expected release datefor SEB 2.1.4?

**Comment by danschlet** [comment]
We are not communicating release dates. Work on SEB 2.1.4 is continuing this week after the release of the new iOS version 2.1.13.

**Comment by danschlet** [comment]
I implemented a fix for this issue: Custom TouchBar settings are disabled while SEB is running, the TouchBar shows the "Expanded Control Strip" and with the Fn key pressed "F1, F2 etc. Keys". When quitting SEB, the previous custom settings for TouchBar are restored.

[Please test, if this works for you.](https://github.com/SafeExamBrowser/seb-testing/tree/master/mac/2.1.4)

**Comment by lifeunexpected** [comment]
I just tested it and it partially works. 
What seems to work is that the custom touchbar gets removed but when you quit SEB it doesnt return the previous settings for touch bar you continue to have "Expanded Control Strip"

**Comment by danschlet** [comment]
Seems that SEB restores TouchBar settings only correctly when the user account running it has administrator rights (not in "Standard" user accounts). I will investigate this further.

**Comment by danschlet** [comment]
Actually it's one specific Touch Bar mode, which SEB cannot switch back automatically, if it is used for the general Touch Bar mode (without fn key), "App Controls". SEB 2.1.4pre4 is displaying an alert while quitting, explaining that users either need to do a restart (login out and in again would probably also work) or set the mode back manually. SEB then opens System Preferences / Keyboard for them.

I hope that Apple reacts on our issue reports and offers an API in future to deactivate custom Touch Bar during the kiosk mode.

But I also realized that BetterTouchTool (BTT, which you also used for your screen shots, as far as I can tell) uses an own method how to reprogram the Touch Bar. To prevent this, SEB terminates BTT and restarts it again when quitting.

**Comment by lifeunexpected** [comment]
> But I also realized that BetterTouchTool (BTT, which you also used for your screen shots, as far as I can tell) uses an own method how to reprogram the Touch Bar. To prevent this, SEB terminates BTT and restarts it again when quitting.
> 
> [You can test this](https://github.com/SafeExamBrowser/seb-testing/tree/master/mac/2.1.4) in the new preview build 2.1.4pre4.

What i could do then is to rename BTT and then SEB wouldnt now it was running so its probably not a good permanent solution.

**Comment by danschlet** [comment]
No, you can't just rename BTT. Test it.

The best permanent solution is to use managed, school owned Macs or iPads for BYOD, as long as Apple doesn't implement a kiosk mode in macOS similarly secure as AAC in iOS. 

You can't secure BYOD Macs perfectly. Someone can build a custom tool, which you won't be able to block, as you don't know it.

BYOD is convenient for institutions, but will never be as secure as buying their own exam devices...

**Comment by danschlet** [comment]
Another solution to prevent Touch Bar tools to reprogram it would be to use the same methods they use. That would probably require much more work (and it might not even work reliably), at least as long there is no good sample code available to find out how they are doing it. As far as I guess, BTT uses some tricks, I don't think there is an official macOS API for tools to reprogram the Touch Bar globally, when other applications are running (besides the standard control strip extensions). I might research this issue further when there is time or we get some helpful hints, but there are more important security improvements to be done in SEB. In general, you always need exam invigilators/proctors, which keep an eye on students and increase the risk for cheating. If students get cheat sheets or messages displayed on their Touch Bar, an exam invigilator could also see that, similar like if they use a smart watch or a smart phone hidden under the table.
