### ISSUE TITLE
Locked my phone SEB

### ISSUE THREAD

**Issue by k2w5r** [SafeExamBrowser/seb-mac#344]
Hi i open “SEB Moodle Demo exam” in that link https://safeexambrowser.org/testing/ and he open safe exam browser and i join the exam and he locked my phone when I want to quit he ask for password but I don’t have password so what can i do?

https://github.com/SafeExamBrowser/seb-mac/assets/152408172/7fd59ff6-c9ad-4115-a1a2-7a54f87b48fb

**Comment by danschlet** [comment]
In almost all of our test exams the quit password is "quit".

In the worst case, you have to do a [force restart](https://support.apple.com/guide/iphone/force-restart-iphone-iph8903c3ee6/ios) of your iPhone/iPad.

I think we should password protect all our testing pages. They are not meant for the public, better don't open SEB links for which you don't have all the passwords...
