### ISSUE TITLE
Audio Autoplay doesn't work on IOS

### ISSUE THREAD

**Issue by dar-brett** [SafeExamBrowser/seb-mac#35]
The particular tests we're running inside of SEB have some media elements that in some specific cases are necessary to be able to understand the question. We'd prefer it if we can make these autoplay, which works in SEB on most platforms, just not IOS - and a lot of our users are using iPads.

I'm not able to find a solid reference for Apple's decision, but based off various posts it appears that IOS blocks autoplay in order to conserve either battery or data.
Similar blog post about video:
https://webkit.org/blog/6784/new-video-policies-for-ios/

It's possible to override this behavior with the UIWebView by adding the follow line SEBWebViewController.m file in the loadView method.
`_sebWebView.mediaPlaybackRequiresUserAction = NO;`
https://developer.apple.com/documentation/uikit/uiwebview/1617954-mediaplaybackrequiresuseraction
I have confirmed this makes autoplay work on my local dev hardware.

Not sure if enabling autoplay as a hardcoded change would be a good idea, or if this should be pulled from the SEB config file.

Does anyone have any thoughts? I can make the change and open a pull request.

**Comment by danschlet** [comment]
I implemented a new setting in SEB 2.1.13 for allowing audio autoplay (Settings / Browser Features / Media Autoplay), by default it stays disabled and you need to enable it (I personally hate all autoplay, but you might have a valid use case for exams).

You can test it by getting access to the TestFlight Beta, see [this page](https://github.com/SafeExamBrowser/seb-testing/tree/master/ios) for more information. 2.1.13 should be released soon as a final version in the App Store, but it's always very welcome if people reporting issues or feature requests help testing fixes/new features in beta versions.

**Comment by danschlet** [comment]
This issue was fixed in SEB 2.1.14.
