### ISSUE TITLE
task bar showing back and forward icons in iPad( though disabled)

### ISSUE THREAD

**Issue by Sharma-Arcadix** [SafeExamBrowser/seb-mac#357]
For Secured exam browser, we have disabled back and forward navigations.
In windows and mac, it is fine, but in iPad the commands are still appearing.
below is the image attached for same.
( we need to hide the command). Please suggest the config or workaround.
![SEBiOS](https://github.com/SafeExamBrowser/seb-mac/assets/136628899/9e8147e5-4f3a-40e1-bff9-cd66e044e36a)

**Comment by danschlet** [comment]
The side menu in the SEB iOS version cannot be disabled. Its function explicitly is to show all active commands (controls for active features), even if the SEB taskbar/Dock and (browser window) toolbar is disabled.

But if you want to disable navigation in the browsing history (back/forward, previous/next web page), there is a separate setting for that, in the **Browser Features** settings page **/ Restrictions in exam tab/new tabs / Allow Navigation**. With that you can separately disable navigation in the exam (the tab in black listed on top in the side menu, there where the Start URL was opened in) and for all additional web pages opened in new tabs. If you disable navigation, the back/forward buttons are either greyed out and not functional or if navigation is disabled both for exam/new tabs, then they are not displayed at all.
