### ISSUE TITLE
Programmatically creating config file

### ISSUE THREAD

**Issue by harveyslash** [SafeExamBrowser/seb-mac#36]
I generated a config file, and I'm trying to make copies using python. 

My seb file is encrypted using a password. 

So the format is : 
**Data Format**

All data in network order (big-endian).

| version | options | encryption salt | HMAC salt |  IV | ... encrypted data ... |   HMAC |

|    0 |    1 |    2-9 |    10-17 | 18-33 |    34 - n-33 | n-31 - n |

version (1 byte): Data format version. For now always 1.
options (1 byte): Reserved. Always 0. 
encryption salt (8 bytes)
HMAC salt (8 bytes)
IV (16 bytes)
encrypted data/ciphertext (variable) -- Encrypted with CBC mode.
HMAC (32 bytes)

However, when i inspect the seb file using a hex editor, the first byte is 31. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/7107410/54082647-ffca6b80-433e-11e9-9ccd-55bf0de58077.png">

Is there something wrong with my logic?

**Comment by danschlet** [comment]
We cannot give this kind of support if you're not at least [Gold Member of the SEB Consortium](https://safeexambrowser.org/consortium/fees.html).
