### ISSUE TITLE
Is anyone else having compatibility issues with IOS 17.3?

### ISSUE THREAD

**Issue by jjack2003** [SafeExamBrowser/seb-mac#367]
Is anyone else having compatibility issues with IOS 17.3?
![Image](https://github.com/SafeExamBrowser/seb-mac/assets/145788902/2880a220-0951-4b87-bf1e-14bb6cd93286)

_Originally posted by @jjack2003 in https://github.com/SafeExamBrowser/seb-mac/issues/321#issuecomment-1932142525_

**Comment by danschlet** [comment]
I guess there is a problem in your settings (although I didn't anticipate this to happen unless you're working at Apple and in fact using an early internal iOS 18 build). So reset your settings (Settings app > SEB > Initiate Settings Reset, start SEB again). 

The setting which would cause this would be in SEB's Settings > Security > Allow Running on iOS Beta. But as long as you're running a current SEB version on iOS 17.x, this error shouldn't happen.

**Comment by jjack2003** [comment]
Thanks for the information.  It seems to be working now.
