### ISSUE TITLE
Library 'SEBSupport' not found while building the SEB

### ISSUE THREAD

**Issue by g-vijayvergia** [SafeExamBrowser/seb-mac#368]
Hi All,

We are planning to create a branding option in the Mac OS app, involving adjustments to color, look and feel, and the ability to incorporate our client's logo into the application. Therefore, we were considering the possibility of creating a customized version. However, during the build process, we encountered an issue where it flagged a missing library with the error message "Library 'SEBSupport' not found."

I'm trying to build the project using XCode 15.2

`ld: warning: search path '/seb-mac/Frameworks' not found
ld: library 'SEBSupport' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Screenshots**
![CleanShot 2024-02-13 at 15 41 08@2x](https://github.com/SafeExamBrowser/seb-mac/assets/43575508/73750b05-4788-485b-ac25-bdb41aac9f21)

**Version Information**
Please complete the following information: 
 - OS: Sonoma 14.4
 - Xcode 15.2 
 - SEB Version 3.3.2

Any assistance or guidance you can provide in the right direction would be highly appreciated. 
Thank you for your time.

Best regards,
Gaurav

**Comment by danschlet** [comment]
See https://github.com/SafeExamBrowser/seb-mac/blob/d8d7c3c7ce797f9240fcf252fbdb56e5bb6867b4/README.md?plain=1#L9.

**Comment by VishnuAthistaraja** [comment]
@g-vijayvergia Could you able to fix the mentioned issue ?
