### ISSUE TITLE
Network filter not consistent between windows and mac version

### ISSUE THREAD

**Issue by kurniawano** [SafeExamBrowser/seb-mac#37]
Hi,
I created a config file to allow certain website access (in this case is repl.it). I tried to scan all the requested URL and put it into the network filter settings. Somehow, it works on Windows SEB 2.2.2, but it did not work on Mac SEB 2.1.3. Here are some details:

Windows:
* SEB 2.2.2
* OS Windows 10

Mac OS:
* SEB 2.1.3
* OS X 10.13.6

Problems:
Windows SEB can access repl.it, but Mac SEB cannot access (run button keeps on loading). 

Expected behaviour:
With the same network filter settings, both should have the same behaviour.

To test:
1. Create an SEB config file.
2. Add the following into the network filter list:
https://www.google-analytics.com
https://api.segment.io/v1
https://repl.it
wss://eval.repl.it/ws
https://www.google.com/recaptcha
https://www.google.com/js
https://storage.googleapis.com
https://www.gstatic.com
https://fonts.gstatic.com
https://cdn.segment.com
https://cdn.polyfill.io
https://fonts.googleapis.com
https://cdnjs.cloudflare.com

3. Try to access repl.it from SEB 2.2.2 Windows and SEB 2.1.3 Mac. 
4. Observation: on Windows, it can load and run button can be clicked. On Mac, the run button cannot load and there is an error of cannot connect.

**Comment by danschlet** [comment]
Did you try to access that side without URL filtering enabled from SEB for macOS?

If it works without URL filtering, can you send us your config file (you can remove passwords)?

**Comment by kurniawano** [comment]
I tried without URL filtering, on SEB for macOS and it did not work. This is the URL:
https://repl.it/language/python3 

I also attached the SEB config file without filtering.

[seb_bug_nofilter_macos.seb.zip](https://github.com/SafeExamBrowser/seb-mac/files/2990760/seb_bug_nofilter_macos.seb.zip)
