### ISSUE TITLE
"Library not found for - ISEBSupport " error while building SEB

### ISSUE THREAD

**Issue by VishnuAthistaraja** [SafeExamBrowser/seb-mac#371]
Getting below given error while building SafeExamBrowser
1. 'Library not found for - ISEB support'
2. 'Linker command failed with exit code 1 (use -v to see invocation)'. 

I downloaded the source code (ZIP) for SafeExamBrowser 3.3.2 on my MacBook Pro running Ventura 13.2.1 from the GitHub release page. 
After extracting the ZIP file, I imported the source code into Xcode 14.3.1. 
I ensured that the code signing settings were properly configured in Xcode. 
Prior to loading the project, I installed CocoaPods version 1.15.0 on my MacBook Pro.

However, when attempting to build the project, I encountered an error stating 'Library not found for - ISEB support' and 
'Linker command failed with exit code 1 (use -v to see invocation)'. 
This issue was not present in Safe Exam Browser version 3.2.5 but is persistent in versions 3.3 and 3.3.2.

MacBook Version : Ventura 13.2.1
SafeExamBrowser Version : 3.3.2
Xcode version : 14.3.1
Cocoapod Version : 1.15.0

1. Download Souce Code (ZIP) for SafeExamBrowser and extract it. https://github.com/SafeExamBrowser/seb-mac/releases
2. Open Extracted project in Xcode by selectin SafeExaBrowser.xcwokspace
3. do code signing settings
4. Create Build

**Expected behavior**
Build need to be sucessfull.

**Screenshots**
![Screenshot 2024-02-14 164141_E](https://github.com/SafeExamBrowser/seb-mac/assets/76390615/3ace1cd5-b1f5-4acb-999d-e903130b4593)

**Version Information**
 - OS: MacOS Ventura 13.2.1
 - SEB Version : SEB 3.3.2

**Additional Context**

Add any other context about the problem here: Same issue observed in and OS Montery 12.6.7 used Xcode version 13.4.1 and Cocopode Version - 1.12.1 

- Always send SEB log files (in directory ~/Library/Logs/Safe Exam Browser/ on Mac) : No log files generated

**Comment by danschlet** [comment]
See https://github.com/SafeExamBrowser/seb-mac/blob/d8d7c3c7ce797f9240fcf252fbdb56e5bb6867b4/README.md?plain=1#L9.

**Comment by VishnuAthistaraja** [comment]
I assumed that the **Safe Exam Browse**r (SEB) should run smoothly without requiring any modifications to its source code, 
as it is open-source software. 
However, it is mentioned in the '_README.md_' that "Binary security modules and Zoom integration (with proprietary licenses) are not included".
We plan to run SEB source code without major changes. We would like to know the specific packages or steps necessary for 
removing them to ensure SEB's successful execution. Additionally, we are open to exploring customization options and 
are prepared to consider "**SEB Alliance Membership**".
