### ISSUE TITLE
Disable Screen Capture on iOS

### ISSUE THREAD

**Issue by bhushan-pasastudio** [SafeExamBrowser/seb-mac#379]
I have disabled the option "Allow screen capture/PrintScreen" in the "Security" settings. This works as expected on Windows, but not on iOS 15.8.2, where I can still capture the screen using SEB.

Is this a known issue or a configuration problem?

I would appreciate any advice on how to resolve this.

**Comment by danschlet** [comment]
Is the Assessment single app mode active? 

How are you capturing, using the iOS screen recording feature or a USB cable?

**Comment by bhushan-pasastudio** [comment]
I am not aware Assessment single app mode. How can I enable this feature?

BTW, first launched the iOS default screen-recorder which starts recording, then launched SEB.

**Comment by bhushan-pasastudio** [comment]
Even swiping to Control Center is also allowing to record.

**Comment by danschlet** [comment]
You have to set a quit password, only then SEB for iOS runs in a secure mode (as stated in the Settings and manual).

**Comment by bhushan-pasastudio** [comment]
I appreciate your assistance, @danschlet. You have resolved the issue. The only problem is that I have to provide the quit password.

**Comment by danschlet** [comment]
Welcome.

Providing a quit password is essential, also for the macOS and Windows versions of SEB:
- [ ] - Without a quit password SEB can be quit at any time. Many exam/test/quiz modules for example in Moodle let students continue an ongoing quiz after logging in again, so it would be really easy to cheat. Even if an assessment software/module prevents re-entering a quiz which wasn't yet submitted, students could unintentionally quit SEB or claim it happened unintentionally (and then quickly look up answers before reporting the "mistake". What do you want to do in that case, fail them for the whole exam?
- Exam supervisors/supporters/the teacher should know the quit password so they can unlock SEB in case of a technical issue (for example WiFi network needs to be reconnected).
- You can use the Quit Link feature in SEB so students can quit SEB after they submitted an exam, see manual on how to use that (Moodle and most systems with SEB integration support that feature automatically).

**Comment by MoniaDi** [comment]
Hello,
Despite having the screenshot option disabled and adding a quit password, it appears that candidates can still take screenshots using MAC devices.
Please advise on what is causing this issue and how we can resolve it. Thanx

**Comment by danschlet** [comment]
Please be more precise. This thread is about the SEB for iOS version. You are mentioning "it appears that candidates can still take screenshots using MAC devices". This seems like a contradiction. If this is about a problem with Mac computers and the macOS version of SEB, then please create a new issue and provide all information the issue template asks for. In this case we would need to see the exact settings used.
