### ISSUE TITLE
Mac App Store version

### ISSUE THREAD

**Issue by danielx** [SafeExamBrowser/seb-mac#38]
Hi,

We've had some schools that had issues with Safe Exam Browser on Mac OS X because they've tried to install it from the Mac App Store.

See link: https://itunes.apple.com/us/app/safe-exam-browser/id411684841
I've noticed that it was last updated in 2012 and the latest version is 1.5.2

I was wondering if there was any chance you could either remove it or update the description to indicate that it wont receive further updates in the Mac App Store.

**Comment by danschlet** [comment]
Surprisingly the Mac App Store version is still being used and downloaded, therefore we cannot just remove it. It will eventually be updated this year. 

Descriptions cannot be changed anymore without uploading a new version, therefore we have to count on people giving their students proper instructions where to download SEB from.
