### ISSUE TITLE
Cmd-S available to students; sometimes leading to freeze

### ISSUE THREAD

**Issue by manrosia** [SafeExamBrowser/seb-mac#382]
**Description of issue:**

Under macOS, students can open the "Save as …" window by pressing Cmd-S. This allows them to browse the Finder. While they cannot open specific files, they can right-click on them and invoke the "overview" (preview of the file's content). This may be misused to cheat in an exam. Other ways of cheating are also conceivable: for example, students preparing a folder/file list containing important keywords.

Moreover, some students (but not all – there is no clear pattern) experience that the underlying LMS (Moodle) and SEB become irresponsive after hitting Cmd-S and closing the "Save as …" window: They are unable to click back and forth through the different pages of a quiz and to access links which should take them to allowed reference material. To resolve this issue, a force shutdown is necessary as neither SEB's quit button nor Cmd-Q works at this stage.

Unfortunately, most of our exams consist of essay-type questions. Therefore, the issue comes up quite frequently because a lot of students are used to regularly hitting Cmd-S to save their progress when working with a word processor such as Microsoft Word.

**Expected behavior:**

Since – in a Windows environment – hitting Ctrl-S does not trigger the "Save as …" window, I feel like the same should be the case on macOS.

**Version information:**
- OS: various versions of macOS; lastly checked on macOS 14.2.1
- SEB: 3.3.2
- LMS: Moodle 4.3.2

**Comment by danschlet** [comment]
Please provide me with a demo exam where I can reproduce this. I tried it with Moodle in SEB 3.3.2  and **couldn't reproduce this.**

**Comment by manrosia** [comment]
Thanks for your swift reply. I created a temporary Moodle account for you and sent the credentials to your ETHZ account (hope this is all right).

**Comment by danschlet** [comment]
I didn't get any e-mail. Please use info at safeexambrowser dot org.

**Comment by danschlet** [comment]
Btw. if Save As can be invoked by the cmd-S shortcut: What is the file which is or could be saved? Does it have a file name? What's the file type? That would be essential information to understand what's going on there.

**Comment by danschlet** [comment]
This should be fixed in [SEB 3.3.3 for macOS](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.3.3). Please test and report if it works for you.

**Comment by manrosia** [comment]
Works perfectly. Thanks for your help.
