### ISSUE TITLE
Inline-Text corrections appear

### ISSUE THREAD

**Issue by cnotz** [SafeExamBrowser/seb-mac#388]
**Describe the bug**
Inline-Text corrections appear on Macos

**To Reproduce**
If inline text proposals is activated on macos  keyboard settings they appear in an exam in safe exam browser.

**Expected behavior**
Inline text proposals should be blocked.

**Screenshots**

**Version Information**
Please complete the following information: 
 - OS: macos sonoma 14.3.1
 - SEB Version [e.g. SEB 3.3.1]

**Additional Context**
It is happening on different machines with different os versions.

**Comment by danschlet** [comment]
See also https://github.com/SafeExamBrowser/seb-mac/discussions/387

**Comment by danschlet** [comment]
This should be fixed in [SEB 3.3.3 for macOS](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.3.3). Please test and report if it works for you.

**Comment by danschlet** [comment]
Ups, seems there is a new issue. Would be great if you could send the logs.

**Comment by cnotz** [comment]
> This should be fixed in [SEB 3.3.3 for macOS](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.3.3). Please test and report if it works for you.

For me it worked. But I just tested it on one machine.
