### ISSUE TITLE
need to remove autofill from search text input on IOS 17, tested on SEB 3.3.2 with demo exam portal page

### ISSUE THREAD

**Issue by visiniaga** [SafeExamBrowser/seb-mac#389]
**IMPORTANT**
Please always consult the documentation first before creating a bug report!
[Manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html) (use find text in browser if you're looking for specific subjects)
[Release Notes](https://safeexambrowser.org/macosx/mac_release_notes_en.html) (for up-to-date information which might not be included in manual yet)

**Describe the bug**
on ios 17, user can acess autofill that open contact and password, this able to open another window beside safe exam browser on iphone

**To Reproduce**
1. Go to [demo exam portal page](https://safeexambrowser.org/exams/)
2. Click on exam
3. click for icon safe exam browser left bottom below 
4. search text
5. hold down, and see menu for autofill
6. open contact

**Expected behavior**
need to should hide autofill

**Screenshots**
If applicable, add screenshots or a link to a video to help explain your problem.

**Version Information**
Please complete the following information: 
 - OS: IOS 17.4 latest
 - SEB Version SEB 3.3.2 latest

**Additional Context**
Add any other context about the problem here: Is it happening on specific machines or OS versions only? How many devices are affected? Did you realize any other pattern?
happening only on ios 17, this may experience problem like this reference
https://github.com/facebook/react-native/pull/43468
autfill can enable student to access window contact outside safe exam browser to look other information on contact

- Always send SEB log files (in directory ~/Library/Logs/Safe Exam Browser/ on Mac, use Settings app / SEB / Initiate Sending Logs to email log files to yourself and attach them here). 
NA

- On iOS/iPadOS, please activate Settings / Privacy & Security / Share iPad Analytics / Share With App Developers, especially if you observed SEB crashes. We then receive anonymized crash reports. 
- Often a test link (send URL and if necessary login/password for a testing/demo account) or an SEB configuration file to reproduce the issue is helpful (remove SEB Quit and Admin passwords!) and compress the .seb file to ZIP to attach here.
NA

**WITHOUT THIS INFORMATION WE USUALLY CANNOT ANSWER YOUR SUPPORT REQUEST!**

**Comment by danschlet** [comment]
Fixed in SEB 3.3.3 for iOS.
