### ISSUE TITLE
White screen after inserting link to moodle exam

### ISSUE THREAD

**Issue by gattegl** [SafeExamBrowser/seb-mac#39]
After inserting the link to my moodle exam and applying the new settings in SEB a white screen appears. The moodle website is not being loaded in the SEB. What could be the problem? I use SEB 2.1.3 and Moodle 3.5.5.

**Comment by danschlet** [comment]
You need to provide more information, this is an unknown issue. Send us the settings file you're using  (unencrypted or indicate the passwords) and we can have a look at it.

**Comment by gattegl** [comment]
Dear Mr Schneider

please find attached the unencrypted config file.



Thank you for your help

**Comment by danschlet** [comment]
Unfortunately I didn't get the attachment, apparently you cannot send those by answering to the GitHub notification emails. You have to upload it here in the web interface.

**Comment by gattegl** [comment]
[SebClientSettings_TEST_TEST.seb.zip](https://github.com/SafeExamBrowser/seb-mac/files/3213217/SebClientSettings_TEST_TEST.seb.zip)

**Comment by danschlet** [comment]
I guess the issue got solved in the meantime? I couldn't find any issue with the config file, besides that when loading it (in SEB 2.1.4, just being released), Moodle shows the error "Ungültige Kursmodul-ID". Or SEB 2.1.4 solves the issue, in case it happened only in SEB 2.1.3.
