### ISSUE TITLE
Unable to access camera

### ISSUE THREAD

**Issue by ARYANRVIMPADAPU** [SafeExamBrowser/seb-mac#400]
**IMPORTANT**
Please always consult the documentation first before creating a bug report!
[Manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html) (use find text in browser if you're looking for specific subjects)
[Release Notes](https://safeexambrowser.org/macosx/mac_release_notes_en.html) (for up-to-date information which might not be included in manual yet)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a link to a video to help explain your problem.

**Version Information**
Please complete the following information: 
 - OS: [e.g. macOS xx, iOS xx]
 - SEB Version [e.g. SEB 3.3.1]

**Additional Context**
Add any other context about the problem here: Is it happening on specific machines or OS versions only? How many devices are affected? Did you realize any other pattern?

- Always send SEB log files (in directory ~/Library/Logs/Safe Exam Browser/ on Mac, use Settings app / SEB / Initiate Sending Logs to email log files to yourself and attach them here). 
- On iOS/iPadOS, please activate Settings / Privacy & Security / Share iPad Analytics / Share With App Developers, especially if you observed SEB crashes. We then receive anonymized crash reports. 
- Often a test link (send URL and if necessary login/password for a testing/demo account) or an SEB configuration file to reproduce the issue is helpful (remove SEB Quit and Admin passwords!) and compress the .seb file to ZIP to attach here.

**WITHOUT THIS INFORMATION WE USUALLY CANNOT ANSWER YOUR SUPPORT REQUEST!**

**Comment by danschlet** [comment]
You have to check:

- Did you allow camera/microphone capture in your SEB settings?
- Are your settings allowing SEB to use the modern WebView? (Try pinch-to-zoom on your website, if that works, it's the modern WebView).

<img width="779" alt="Screenshot 2024-05-06 at 15 08 58" src="https://github.com/SafeExamBrowser/seb-mac/assets/2464749/c840a4fb-989b-42ab-80ff-8670cea4ddee">

**Comment by danschlet** [comment]
**PS: IN FUTURE WE WILL IGNORE ISSUE REPORTS WITHOUT A PROPER DESCRIPTION!!!**
