### ISSUE TITLE
Default UserAgent not getting added when link is open under SEB.

### ISSUE THREAD

**Issue by VarunTwri** [SafeExamBrowser/seb-mac#402]
**Describe the bug**
We want to restrict user so that SEB with our start link only opens with our configuration.
No user should be able to configure our link on their config file and open it.
For this we made check for user agent what SEB adds by default.
![image](https://github.com/SafeExamBrowser/seb-mac/assets/102298041/9cb12011-fca5-4605-9c9c-3dd2a7eab01b)

But this "SEB" text is not getting appended for IOS userAgent.
We are getting below userAgent.
![image](https://github.com/SafeExamBrowser/seb-mac/assets/102298041/b6712e5e-eee7-4303-90c4-2edfa87f4c69)

Updated to SEB IOS 3.3 then its fine, but still users can have old version and do setup our link.

**Expected behavior**
Default UserAgent should be appended with "SEB" text and version. 

**Version Information**
Please complete the following information: 
 - iPadOS 17.2
 - SEB Version : SEB 3.3.2

**Comment by danschlet** [comment]
Are you saying it works correctly with SEB 3.3.3 but not with 3.3.2? We obviously cannot fix an older SEB version, students have to update to the latest version.

What assessment system are you using? I assume your SEB integration or SEB settings don't allow SEB to use the modern WebView. In SEB 3.3.3 a deprecation message is displayed on top of the browser tab.

If you update your SEB integration or SEB settings to allow SEB to use the modern WebView, then the user agent should be correct also in SEB 3.3.2. The reason for the missing user agent isn't SEB, but that Apple is no longer fully supporting the classic WebView (UIWebView). In SEB 3.3.3 we implement a workaround for that, but the old WebView will likely soon be removed completely from iOS.

**Comment by VarunTwri** [comment]
This is fine.
To remove  deprecation message if we set "PreferModern" then its not sending Config and BEK keys in header for mac/ios.
How can we validate for legit config is used?

**Comment by danschlet** [comment]
Come on, we wrote about this everywhere, on the [homepage news section](https://safeexambrowser.org/news_en.html), download page, release notes. Please read our documentation.
