### ISSUE TITLE
Downloading and Opening SEB Configuration Not Allowed

### ISSUE THREAD

**Issue by adixy94** [SafeExamBrowser/seb-mac#417]
**Describe the bug**
The SEB displays the warning "Downloading and Opening SEB Configuration Not Allowed!" when launched using the SEBS protocol even if the "downloadAndOpenSebConfig" setting is true.

**To Reproduce**
1. Launch the SEB using the SEBS protocol
2. SEB displays the warning "Downloading and Opening SEB Configuration Not Allowed!" 

**Expected behavior**
SEB displays the exam.

**Screenshots**
The screenshot of the warning is below
![screenshot](https://github.com/SafeExamBrowser/seb-mac/assets/35684078/e2348063-57fb-43be-bc3a-619d6cd7bd42)

**Version Information**
Please complete the following information: 
 - OS: macOS Version 14.5 (Build 23F79)
 - SEB Version:  Safe Exam Browser version 3.3.2 (Build 1490B)

**Additional Context**
The student upgraded from macOS 13.2.1  to 14.5 and reinstalled the SEB, but the same warning appeared. The warning appears only for this student.

SEB log:
[org.safeexambrowser.SafeExamBrowser 2024-05-27--19-07-18-752.log](https://github.com/user-attachments/files/15865942/org.safeexambrowser.SafeExamBrowser.2024-05-27--19-07-18-752.log)
Configuration file:
https://hllqp.com/certification/sebsettings/mac/dEllaFpDQTBXOUtlMXBUcG9hWnBTMHh2enlmdXNsYmZhbk4rOHF6dHVmTT0=

**Comment by danschlet** [comment]
That student somehow managed to disable opening SEB configurations in their SEB client configuration. Either manually by playing around in SEB's settings menu or by opening some SEB client configuration which has that setting enabled. This is apparent in the log file:

2024/05/27 15:07:19:066  Attempted Downloading and Opening of SEB configurations is not allowed in current settings

Just [reset SEB client settings](https://safeexambrowser.org/macosx/mac_usermanual_en.html#ConfigDeployment) (also mentioned [in FAQ](https://safeexambrowser.org/faq/faq_en.html#MacOSX), although inside a paragraph), use this line in Terminal:
`defaults delete org.safeexambrowser.SafeExamBrowser`

**Comment by danschlet** [comment]
Since macOS 14 Sonoma, you again have to just delete the org.safeexambrowser.Safe-Exam-Browser.plist file in the Preferences folder (~/Library/Preferences/), Apple changed that.

**Comment by yiemyi05** [comment]
Hola. Es necesario que cada vez que use el programa elimine el archivo? Tengo estudiantes que me están informando que tienen el mismo error aún cuando lo han eliminado. 

> Desde macOS 14 Sonoma, nuevamente debes eliminar el archivo org.safeexambrowser.Safe-Exam-Browser.plist en la carpeta Preferencias (~/Library/Preferences/); Apple cambió eso.
