### ISSUE TITLE
Allow text search in Browser (Mac) rendered PDFs

### ISSUE THREAD

**Issue by brunobaudry** [SafeExamBrowser/seb-mac#423]
**Describe the bug**
Searching inside browser rendered PDF doesn't yield any result as it does on the Windows version.

**To Reproduce**
A. With SEB 4 Mac :
   1. "Allow text search" Browser config ticked.
   2. "Allowing downloading and uploading file ..." "Allow usig acrobat..." unticked. (PDF rendered in SEB).
   3. Open Web page that has a link to a PDF, the PDF is rendered in SEB.
   4. Fill in an identical text that you can read (and that is selectable, not pixelised) in the PDF in the search field.
   5. Click the magnifier.
   6. Acknowledge that no result yields.

B. Reproduce the steps with SEB 4 Windows and acknowledge in step 6 that results yield.

**Expected behavior**
The behaviour of "Allow text search" should be platform agnostic (if feasible indeed) for fairness when student are performing an exam.

**Version Information**
 - OS: 14.5
 - SEB Version 3.3.3

**Comment by brunobaudry** [comment]
indeed with "Classic" engine settings... Now reading @danschlet  feedback on issue #299 it will not work. 
The issue we had is that hte rendered embedded PDF in moodle are 10% of the size. And we could not find the way to mitigte that... Any clue ? (I will paste a screen shot)

**Comment by acamacho-unige** [comment]
> indeed with "Classic" engine settings... Now reading @danschlet feedback on issue #299 it will never be fixed with the classic engine. The issue we had is that hte rendered embedded PDF in moodle are 10% of the size. And we could not find the way to mitigte that... Any clue ? (I will paste a screen shot)

If you talk about a problem regarding PDF files showing in very small (taking 1/4 of the window) we only had this problem when using Moodle Folder Ressource. When opening PDF files that did not come from a Folder Resource they showed up correctly.

**Comment by brunobaudry** [comment]
Yes @acamacho-unige thanks for the feedback ! And actually when needing to open several PDF and opttion/ctrl + tab to switch between windows is not possible with PDFs in Moodle's Resource Folder. So all needed PDF for an open have to be as simple file resource.
