### ISSUE TITLE
Tab Crash in Firefox

### ISSUE THREAD

**Issue by srineer-toddleapp** [SafeExamBrowser/seb-mac#425]
**Describe the bug**
While opening any link of seb in firefox in mac, we are getting a tab crash error. This is happening only with seb deeplinks and not other links.

**To Reproduce**
1. Open firefox in mac
2. Try to open a deeplink of seb either the demo link in https://safeexambrowser.org/testing/ or any link that opens seb.
2. You will be able to open the exam.
3. But once you quit the exam, you can see that the tab has crashed in firefox. with the error "Gah. Your tab just crashed."

**Expected behavior**
The tab should not crash and work as expected. 

**Screenshots**
[Uploading screen-capture.webm…]()
<img width="1728" alt="Screenshot 2024-07-15 at 12 06 12 PM" src="https://github.com/user-attachments/assets/c779eeb3-d887-4227-b762-862d46305b1a">

**Version Information**
Please complete the following information: 
- OS: macOs 14.1.1
- SEB Version: 3.3.2

**Comment by danschlet** [comment]
When using the standard kiosk (lockdown) mode, SEB has to block the networking process of web browsers (to prevent for example web-based conferencing systems or screen sharing). Firefox reacts with this message. You can just reload the tab (at least last time I tried it). 
As an alternative you can add a prohibited process (Applications tab in settings) for Firefox itself, then the whole browser will be quit when SEB runs. 
Or use the macOS AAC Assessment Mode for lockdown (see Security tab in Settings). Then no processes have to be quit (they won't have internet access while SEB is in this mode).
