### ISSUE TITLE
iPad OS 18 doesnt support this app.

### ISSUE THREAD

**Issue by RifaJoy** [SafeExamBrowser/seb-mac#433]
![IMG_0598](https://github.com/user-attachments/assets/e63cc5d6-c101-4e3f-9926-fec35e10cc99)
According from the picture, my ipad doesn't support this aplication, maybe devoloper can fix it that bug.

![IMG_0600](https://github.com/user-attachments/assets/fb186f7a-1278-4bdf-a79a-1533ed30341f)
![IMG_0599](https://github.com/user-attachments/assets/54fe62a1-5853-4b7b-9420-2c97c3f8dc9a)

**Comment by danschlet** [comment]
See https://github.com/SafeExamBrowser/seb-mac/issues/416. Either settings can be changed to allow to run on iPadOS 18 (still a beta/RC) or the TestFlight beta of SEB 3.4 can be used, [see this link](https://testflight.apple.com/join/egxLmc4j).
