### ISSUE TITLE
Text zoom vs page zoom

### ISSUE THREAD

**Issue by TomJampen** [SafeExamBrowser/seb-mac#436]
Hi Daniel

Under SEB 3.3.3 (and maybe before as well) and macOS Sonoma 14.5 the zoom settings are not working properly:

When enabling "showMenuBar" the text zoom and page zoom options in the "Darstellung" menu (probably "view" in english) do exactly the same thing, while page zoom should (in my opinion) work like a magnifying glass (as pinch zoom on the touchpad does).

However, the SEB config settings "enableZoomPage" and "enableZoomText" work correctly, e.g. setting enableZoomPage to false correctly disables pinch zoom on the touchpad (in addition to the page zoom options in the menu "Darstellung").

Furthermore, the tooltip in the SEB config tool  lists the wrong keyboard shortcuts (cmd +/- and ctrl-cmd +/-) at least for a german macOS, while the macOS menu "Darstellung" lists the correct ones.

Kind regards
Tom

**Comment by danschlet** [comment]
Text zoom is not supported by Apple in the modern WebView (WKWebView). I implemented a workaround, which has quite some limitations (the tooltip in the Settings menu lists that, basically text zoom works only on some very simple websites). I think I will remove the option completely unless Apple provides a proper API for this in WKWebView.
But on my simple test page it still works as expected. Apple changed the shortcut on Swiss German keyboards a few macOS versions ago. I didn't adjust it in the settings UI, will add some remark there. In the menu, the operating system shows the correct shortcuts.

**Comment by TomJampen** [comment]
Thanks for your reply. "Text zoom" works indeed, I only talked about "page zoom" or that they both do the same for me (when using the keyboard shortcuts or the menu).

But when I use the pinch zoom function of the touchpad (spread two fingers), the behavior is different. I expected that behavior to be "page zoom" as the entire page is zoomed. My expectations were supported by the fact that when disabling page zoom in the settings, pinch zoom on the touchpad no longer works. That's why I thought, page zoom shows unexpected behavior.

Sorry, I haven't been able to find the mentioned limitations in the settings.

The background of this bug report is the following:
Because of the pinch zoom funtionality on mac we are having strange effects in VMs shown on the exam website. We are thinking about disabling page zoom (in order to disable the pinch functionality on mac and preventing an unusable zoomed-in VM). But I wanted to check with you first whether it is really a bug or expected behavior (page zoom = text zoom), before we change our SEB config...

**Comment by danschlet** [comment]
Text zoom is supposed to only change text sizes, not images. Page zoom also increases the size of images, but still keeps the overall width of a web page. This is the difference to the pinch feature on the trackpad, which is a "real" zoom for the entire page. 

Originally the behavior in SEB was the same as in Safari (text zoom there is called "Make Text Bigger" or "Make Text Smaller", sometimes only displayed in the View menu when holding the option/alt key). But there it also seems to work differently depending on the website, on GitHub both zoom in and make text bigger also change the size of image elements, whether on https://demo.safeexambrowser.org/exams/ it behaves same as in SEB.

Anyways, in SEB I bound disabling the pinch-to-zoom feature to disabling page zoom, as there were people which wanted to disable all kinds of zooming for specific exams. Theoretically I could also add a separate setting for disabling pinch-to-zoom, but I'm very hesitant adding even more settings. Especially if they would only work in the Mac version and not on iOS and Windows (we are supposed to keep features as much as possible aligned between SEB platforms).

Do you really need zoom/text zoom capabilities in those exams which use VMs? Why not just disable it completely?

**Comment by TomJampen** [comment]
OK, thanks you very much, that explains a lot. I don't have or use a macbook, thus I can only test for a short time on student devices.

I will disable page zoom. I'll probably leave text zoom enabled for accessibility.

Kind regards
Tom
