### ISSUE TITLE
SEB freezes on a white screen

### ISSUE THREAD

**Issue by Fra-bon** [SafeExamBrowser/seb-mac#452]
![PHOTO-2024-10-28-09-51-58](https://github.com/user-attachments/assets/50c4197a-436f-4c20-b2ba-3b13684beb1e)
Hi, 
I’m a macbook pro 2019 user, after I log-in with my university account, SEB freezes on a white screen (like in the photo). I restart my pc lots of times, I deleted all type of file related to SEB, before I reinstalled it.
 Somebody can help me?

**Comment by moehzhaw** [comment]
According to some tutors, we've had this problem several times since December 2024.

**Comment by danschlet** [comment]
Please send all the information requested in the GitHub issue template (log files, macOS version used, steps to reproduce). Otherwise we cannot analyze the issue and will close it.

**Comment by moehzhaw** [comment]
logfiles see #470
