### ISSUE TITLE
Sustained keypress and SEB

### ISSUE THREAD

**Issue by a-camacho** [SafeExamBrowser/seb-mac#46]
Dear SEB developper team,

While doing some BYOD exams we observed a feature that can't be used in SEB.
We would like to know if it could be integrated, or if something prevents it from being possible.

For example, a student using a Mac OS X computer configured to use only English UK keyboard for example, usually inserts special characters (éèëê or áàäî, etc.) using "sustained keypress". Pressing a key and keeping pressing it usually suggests some special characters using the same letter.

I think chinese keyboard also uses this feature (of suggestions depending on key strokes) and we would like to know if those suggestions could be used with SEB.

Sorry if this answer has already been answered, couldn't find anything about that.

**Comment by danschlet** [comment]
Unfortunately this feature isn't compatible with the current SEB kiosk mode, the popup window is displayed underneath SEB's windows and thus invisible. 

SEB 2.1.5 will support the new AAC single app kiosk mode available as of macOS Catalina 10.15.4. I assume the keyboard popup is compatible with Apple's own kiosk mode. I'll try it out later this week when finalizing SEB 2.1.5.

**Comment by danschlet** [comment]
I think Apple didn't consider keyboard popups in the AAC kiosk mode unless it was fixed in latest macOS versions. I will retest and report to Apple in case it still doesn't work.
