### ISSUE TITLE
Seb  2.1.4 bettertouchtool

### ISSUE THREAD

**Issue by hypoflex** [SafeExamBrowser/seb-mac#47]
seb disables BTT and gave a message about restoring this. but after loading the configuration file given by school i've been unable  to recreate the message. 

so how to i restore my BTT to work again.
even after restarting my mac i keep getting the default touch bar and been unable to find how to fix  it.
it somewhere stated i've got to go into keyboard settings, but cant  find touchbar related settings  there.

**Comment by danschlet** [comment]
You have to change the setting "Touch Bar shows" once again to "App Controls" (even though this option might already be displayed, you have to select in manually again). See screenshot below. Do you really don't have this option on your Mac?

<img width="780" alt="Screen Shot 2020-01-16 at 00 18 54" src="https://user-images.githubusercontent.com/2464749/72450900-14e11800-37f6-11ea-83e8-4620fb25c66c.png">

Better Touch Tool is not disabled by this option though, SEB has to terminate BTT while running. When quitting, SEB restarts BTT. If that should fail, then rebooting will definitely let BTT run again, as SEB doesn't remove it from the apps which are started automatically.

**Comment by hypoflex** [comment]
apparently SEB did  change this option, after changing this BTT is working again.
i'll will see after tomorrow's exam what btt does

thanks for your reply

**Comment by hypoflex** [comment]
i've succesfully restored the touchbar after exiting the program.  sadly i was unable to make the exam using SEB, after clicking start exam it prompted me with a error  saying i should  be using SEB  to make the exam even though i was.

**Comment by danschlet** [comment]
The error saying that you should be using SEB sounds like the exam system has an issue to recognize the SEB version. Which exam system or learding management system are you using?
