### ISSUE TITLE
dictionary lookups

### ISSUE THREAD

**Issue by bongus22** [SafeExamBrowser/seb-mac#5]
Hi,
I'm currently testing with Mac OS Sierra (10.12.4) and it seems with both SEB 2.1 and 2.1.2 for mac, the "Allow spell checking" and "Allow dictionary look up" options do not work.

I'd be happy to help test a fix. Great product BTW.

Thanks,
Angus

**Comment by danschlet** [comment]
Fixed in SEB 2.1.3 for macOS.
