### ISSUE TITLE
SEB security verification fails after network loss

### ISSUE THREAD

**Issue by a-camacho** [SafeExamBrowser/seb-mac#53]
**Description of the use case**

- A student starts a BYOD exam, with a MAC computer (only).
- He then, disables his WIFI connexion (loosing internet).
- He then, tries to access next question (buttons become disabled, error explanation is showed)
  - IMPORTANT : WHILE DISCONNECTED ...
  - He flags and unflags the question multiple times.
  - He tries to access other questions (using cards)
- He then, recovers internet (with same network, or other network)
- He then, refreshes the page (because everything is frozen, only option)

**Expected result**

- Student (as on Windows) should be back on the quizz attempt, same question, but loosing all unsaved data.

**Observed result**

- Student (on Mac OS X) gets a error (cf image) and gets kicked out of quizz.
- After clicking on continue two times (student did not lost his session) he can come back to the quizz. Of course loosing all unsaved data.
- Two extra clics and a red error on Moodle, that only shows in SEB for Mac OS (2.1.3 or 2.1.4 tested) and if we are using SEB config keys.
- We also tried using the secondary SEB config key (mac os specific) but same issue exists.

**Comment by a-camacho** [comment]
Here is the error the student sees, when reloading page to get back to quizz.
Windows computers doing the same clicks are able to get back to the quizz, without seeing a Moodle warning like this one.

![picture](https://user-images.githubusercontent.com/29976133/75768546-d91df580-5d44-11ea-91db-0495208b1b43.jpeg)

**Comment by danschlet** [comment]
That must be a bug in the Moodle quiz access rule plugin. SEB doesn't change anything regarding the Browser Exam Key (or Config Key, which isn't supported by Moodle yet) if the network connection is lost. Please file an issue report at https://github.com/lucaboesch/moodle-quizaccess_safeexambrowser
