### ISSUE TITLE
Looking for ways to disable communication programs

### ISSUE THREAD

**Issue by ramonavic** [SafeExamBrowser/seb-mac#54]
Dear SEB team, 

Since the Corona crisis we at Learnbeat see an increased interest in taking exams remotely for our market, mainly high schools. 
The problem is that students have found ways to fraude. 
We are trying to eliminate the following issues, but I was wondering if we 

This is mainly that they can still use apps like Zoom, Skype or Teams to communicate with each other whilst SEB is being launched. 
The communication can be either through the native app or through the webapp in the browser. 

On the Mac version of SEB we can't disable any applications. Is there another way to lock the above mentioned apps from communicating? We would like to keep our internet connection active. Is the disabling of applications for Mac on your roadmap?

On Windows we can successfully terminate the native apps, which is great, but we can't terminate the whole browser.  This is because we would like to redirect the user back to our own webapp in the browser. Do you have any recommendation on how to terminate the communication between these apps? We have blocked capturing audio on Windows, but that doesn't seem to do the trick. Is there maybe a way to terminate all browser tabs except the ones with our own domain? 

I hope you have time to look at this!
Kind regards, 

Ramon

**Comment by danschlet** [comment]
Hi Ramon,

It is not easy to block unwanted apps in BYOD scenarios, I explained the challenges in previous posts (here or in our SourceForge forums). Answering your questions in short:

- Yes, in SEB 2.2 for macOS you will be able to specify prohibited processes and we will add some default ones, similar to the Windows version. I'm also evaluating the opposite system, for SEB to prohibit all non-macOS processes and you could permit specific ones. On macOS, that's possible, as all system processes are code signed (in Windows, not all are). But this might cause issues with third-party hardware drivers and tools running in the background, we will have to test how well this works in a real-world scenario. SEB 2.2 is delayed, we had to push the release to sometimes in Q2 2020.
- Already the next macOS update 2.1.5 is supporting the new Assessment Mode available in macOS 10.15.4 Catalina. In this mode, only the Apple-authorized assessment app can communicate over the network, all other applications don't have any network access while the exam is running. I think this will be way more secure than all our kiosk modes in the Windows and Mac versions. This SEB version should be released in the next couple of weeks.
- In Windows, you have to decide: Either you allow the browser to run and risk that some tools might record the screen (although it seemed that many of them cannot record the desktop SEB is running on with the default kiosk mode "Create new desktop"). Or you can terminate all browsers and rely on your students to start their browser and your web app again, there's no way to terminate specific browser tabs for SEB. Maybe your web app could do that in a browser with some Javascript code?
- Theoretically SEB on Windows could restart some browser when the exam is finished, that might work with the Additional Resources feature and with reconfiguring the exam session (this is a bit an experimental capability of the Additional Resources feature).

**Comment by ramonavic** [comment]
Hi Daniel, 

Thank you for your quick reply. 
We will look into the restarting the browser after the exam is done. 
And we will also look into the minimizing the network access for MacOs, sounds interesting!

**Comment by danschlet** [comment]
Since SEB 2.2.1 for macOS, prohibited processes are also supported on Mac.
