### ISSUE TITLE
Safe Exam Browser and Microsoft Teams

### ISSUE THREAD

**Issue by eliazarx** [SafeExamBrowser/seb-mac#58]
Good morning!
We are testing SEB 2.1.4 to allow students to take online exams via moodle.
Unfortunately we have noticed that this version of SEB does not close Microsoft Teams (macOS 10.15). Microsoft Teams continues to operate and manage a video call even after SEB was started.

On windows everything works regularly.

Best regards.

**Comment by danschlet** [comment]
SEB 2.1.4 for macOS only prevents most screen sharing solutions, not video calls, as long as they were started before SEB and as long as they don't require user interaction (which is blocked as long as SEB is running).

But SEB 2.1.5, which will be released in the next few days, stops all video, audio and other communication applications when running on macOS 10.15.4 or newer and most such applications (configurable) when running on older macOS versions.

**Comment by danschlet** [comment]
Since SEB 2.2.1 for macOS, prohibited processes are also supported on Mac and Microsoft Teams is one of the preset prohibited processes which are quit when SEB starts.
