### ISSUE TITLE
Safe Exam on Mac

### ISSUE THREAD

**Issue by ITsuppport** [SafeExamBrowser/seb-mac#6]
Safe Exam Browser regarding any planned updates that will allow MAC users to swap between languages as PC users can currently do?

Are you aware of a fix for Mac users or do you have an ETA

**Comment by danschlet** [comment]
In a future SEB for macOS version there will be widgets for changing keyboard language, reconnecting to WiFi networks and showing battery status. Until then use the option "Show menu bar" [as described in the manual](http://safeexambrowser.org/macosx/mac_usermanual_en.html#AppearancePane).
