### ISSUE TITLE
iOS WebView breaks css after showing on screen keyboard on iOS 13.4 and up

### ISSUE THREAD

**Issue by t00** [SafeExamBrowser/seb-mac#60]
Similar issue has been registered on Cordova when using UIWebView, SEBWebView seems to be affected by the same problem.
[See the Cordova bug](https://github.com/apache/cordova-ios/issues/796)
When on screen keyboard is shown animations break and other css-related issues happen due to a bug in WebKit.
This is confirmed to be fixed in WKWebView. Do you have any plans to switch to WKWebView? I guess it requires separating iOS and macOS WebView code?

Tested on seb 2.1.16 and iOS 13.4 and 13.4.1.

**Comment by danschlet** [comment]
As indicated in our [roadmap](https://safeexambrowser.org/about_roadmap_en.html), SEB 3.0 for iOS and macOS will use WKWebView.
