### ISSUE TITLE
Switch between SEB and One Particular App on OSX

### ISSUE THREAD

**Issue by onato** [SafeExamBrowser/seb-mac#62]
I need to run SEB along with GoToMeeting so the user can share their screen and chat with their Proctor. I can start the GoToMeeting and then SEB. This allows me to share the screen, but I need a way for the user to use the chat function.

As far as I can see, at present, it is only possible to allow switching between all running apps and rely on the OSX setting to restrict which applications are allowed to run.

Is there any way to restrict the user to SEB and one other app without relying on the OSX parental controls?

**Comment by onato** [comment]
It see that there is some commented out code that kind of does what I am after. It was commented out 8 years ago, though, so I wonder if that strategy has been abandoned. I imagine this would be the spot to filter applications by the list you provide in the application preferences.

https://github.com/SafeExamBrowser/seb-mac/blob/ecd1db30cc1bdbcb6ee778614105f9d8a7828d42/Classes/SEBController.m#L3113-L3130

I do really need this, so I would be happy to invest time to help move this feature along.

**Comment by danschlet** [comment]
There is no way to run other applications securely in parallel with SEB on macOS, other than by using a separate user account with set up parental controls. If you search our forums at https://sourceforge.net/p/seb/discussion/, you will found posts where I explained why.

Here I discussed what our approach for remote proctoring with SEB is: https://sourceforge.net/p/seb/discussion/3704033/thread/207ec42694/
