### ISSUE TITLE
camera not working in macOS Catalina version 10.15.6.

### ISSUE THREAD

**Issue by laralb** [SafeExamBrowser/seb-mac#63]
I am using  macOS Catalina version 10.15.6. we try to open camera using safe exam browser it’s not working.

**Comment by danschlet** [comment]
Apple doesn't allow to use getUserMedia in embedded web views, therefore this is not possible in SEB for macOS.
Here is more information: https://sourceforge.net/p/seb/discussion/3704033/thread/207ec42694/

**Comment by sevatrofimov** [comment]
is it not a solution https://github.com/fathyb/JSCameraKit ?

**Comment by danschlet** [comment]
See this issue https://github.com/SafeExamBrowser/seb-mac/issues/66.
