### ISSUE TITLE
When will SEB be allowed to run on iOS 14?

### ISSUE THREAD

**Issue by infinytum** [SafeExamBrowser/seb-mac#69]
It kinda sucks when you are an apple iOS developer and then need a second iPad just to do exams. Compiling the thing myself works but it crashes on launch...

Are you waiting for the official release of iOS 14 or can we do anything to bypass that?

**Comment by danschlet** [comment]
You can thank Apple for that, because they had bugs in earlier iOS beta versions which made SEB insecure (once the single app mode didn't work at all), therefore we had to introduce this setting.

You can just tell your exam organizers to include the setting (which is of course [mentioned in the documentation](https://safeexambrowser.org/ios/ios_usermanual_en.html) and release notes, just read it...): 
	<key>allowiOSBetaVersionNumber</key>
	<integer>14</integer>
in their exam settings, then the current version will run on iOS 14 (by now this should be without risk). 

And yes, we will release a version without this restriction in time before the final release of iOS 14.

**Comment by danschlet** [comment]
Unfortunately Apple surprised us (and all other developers) by not giving us the usual 7 days to submit updated apps before releasing iOS 14... We submitted an update 2.1.17 to the App Store yesterday which will run on iOS 14 by default (without having to use the special setting), but we're waiting for Apple to review and approve it on the store. Usually this takes around 24 hours, but as now many developers submitted app updates for iOS 14, I fear that it might take longer this time.

If you can't easily let that allowiOSBetaVersionNumber = 14 setting be added to your exam settings, you could use the SEB for iOS 2.1.50 TestFlight beta version for now, which runs by default on iOS 14. If you send me your name and email address, I can add you to the TestFlight (I think GitHub still doesn't support private messages, you can also use info at safeexambrowser.org or the SourceForge forum).

**Comment by infinytum** [comment]
Hey! Thank you for the quick update!

I was surprised myself when I watched the stream and they announced "Tomorrow". As long as the client update is out in the next 3 weeks I'm fine though :) 

BTW: Is it normal that I cannot run the code myself with XCode? Kinda crashes on boot with BAD_ACCESS x0... I guess it makes sense not everyone can just run a modded version of this ^^.

**Comment by danschlet** [comment]
Yes, Apple wasn't really nice to us developers...

Did you check out the SEB-iOS branch? That's the one for the current stable version (master currently is only the macOS version, but I will merge the branches soon, so there will be Mac and iOS targets in one unified workspace file).

There are several possible reasons why an own build can crash (and I can't go into too much detail, as you correctly guessed 😉 ). It should generally be possible to run the code, but for it to work properly, you would need to create a correct provisioning profile. You wouldn't be able to use it for an exam without a lot of hacking, I wouldn't recommend it (and we are of course hardening some security measures regularly with new releases, for obvious reasons...).

**Comment by danschlet** [comment]
The issue was fixed in SEB 2.1.17 for iOS.
