### ISSUE TITLE
MacOS 10.15 SEB 2.2.1 and Acrobat Reader DC

### ISSUE THREAD

**Issue by michaelhq** [SafeExamBrowser/seb-mac#71]
Dear developers of SEB

There is an issue with MacOS 10.15 and SEB 2.2.1 with PDFs.

With SEB 2.2.1 PDFs cannot be displayed in the same or a new window if Acrobat DC or Acrobat DC Reader is installed. Even after uninstalling Acrobat the issue remains. The SEB windows are empty and no PDF is displayed.

Regards
Michael H. Quade

**Comment by danschlet** [comment]
The problem with displaying PDF files when Adobe Acrobat Reader is installed is solved in SEB 2.2.2 for macOS: https://safeexambrowser.org/download_en.html#MacOSX
