### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by jhgpretorius** [SafeExamBrowser/seb-mac#72]
After succesfully entering my exam room, the Safe exam browser close unexpectedly and showed a message that said: You have installed Safe Exam Browser, but it isnt configured yet. This is on Mac. I don’t understand as I downloaded SEB from a link from the British Council and gave all permissions (webcam, etc) needed. Help would be appreciated.

**Comment by danschlet** [comment]
Ask British Council for instructions how to start their exam. Exams is SEB can be started in different ways, so you always have to ask your exam provider for detailed instructions, we don't know how they configured their exams and we are not directly associated with them.

If they provided you with a special link or configuration file to start the exam in SEB, then open/click that file or link. If you clicked that link and SEB started with that page "isn't configured yet", then quit SEB (button on the bottom right or cmd-Q) and click the link a second time.
