### ISSUE TITLE
Stile App Website Not Accessible.

### ISSUE THREAD

**Issue by jamesdundon** [SafeExamBrowser/seb-mac#75]
When trying to access this website (https://stileapp.com/) with the mac version of the browser it just hangs on the loading screen. It works fine on the windows SEB browser.

Thanks

**Comment by danschlet** [comment]
The current Mac and iOS versions of SEB use an older embedded web view (the WebKit1 browser engine). SEB 3.0 (will be available early next year) will be using the newer WKWebView (WebKit2), which is also used by current versions of Safari. 

Web applications which use the latest web technologies might therefore not run on current SEB versions for Mac/iOS, unless they are made compatible with older Safari versions. Most likely such web apps will run with SEB 3.0 again on Mac/iOS.

But note that Apple doesn't allow to use some web technologies in embedded web views (this applies also to the newer WKWebView), even if they work in Safari. For example WebRTC will only work starting macOS 11.1. Service Workers are still not supported, so you cannot use web applications with SEB which depend on Service Workers.

**Comment by jamesdundon** [comment]
Thanks for your feedback.
