### ISSUE TITLE
Beginner question: how do I create a seb file to send it to my students?

### ISSUE THREAD

**Issue by jlawgit** [SafeExamBrowser/seb-mac#79]
I have combed through the website and manual, and I cannot find any examples on how to make the seb config file or an example that can be downloaded.

Also, webcam function is important, if not implemented, I guess our option is to ask students to prop their mobile phone and show their writing area?

**Comment by danschlet** [comment]
I recommend to use an assessment or learning management system with built-in "one-click" support for SEB like Moodle 3.9 or newer or a commercial system like Inspera Assessment. 

We cannot teach people how to use SEB, if you read our documentation thoroughly and try it out yourself, you should be able to find it out, or google for external resources how to use SEB.
