### ISSUE TITLE
Frame load error

### ISSUE THREAD

**Issue by pmasawe** [SafeExamBrowser/seb-mac#8]
Hi we are having issues with the new version 2.1.11 for iOS where we are prompted by the error message "Frame load error" when starting Safe Exam Browser on iPads. Not all iPads are affected by this error so maybe it has to do with certain iOS updates?

Best regards,
Patrick

**Comment by danschlet** [comment]
A "Frame load error" usually has to do with server or network issues, maybe some HTML/CSS/JavaScript is more likely to induce those errors too.

As we didn't change nothing at all in the code of the web browser part of SEB for iOS 2.1.11 (compared to 2.1.10), it most likely has to do with some changes in the iOS version used. Do you see some pattern on which iPads it happens? Do those use another iOS version than the ones where it doesn't happen?

Which exam system or LMS are you using? Maybe it's just a server load problem. Was there a higher number of participants in the test when it happened? Was it done in another location or was the WiFi infrastructure changed?  Are you using some other clients to connect to that servers? Maybe other platform versions of SEB? 

In general online exam systems should have some network stability tolerance or resilience functionality build in. WiFi can always have issues (often only temporarily) and in the past we observed all kinds of server load or answer time issues (even if load tests were successful) or even cases when even redundant network switches failed and it first looked like a browser issue. Real exams can differ significantly from automized load testing.

This kind of issues are almost impossible to track down, as long as we don't get more information and if we can't reproduce them. If we see some pattern when those issues happen and when not, this could help us too.

Best regards,
Daniel

**Comment by pmasawe** [comment]
Thank you very much for your quick and informative answer! It seems like we may have some bad Wifi going on as you pointed out. I will come back to this thread if I am able to provide more information.

All best,
Patrick
