### ISSUE TITLE
Need Safe Browser version 2.4.1 for Macbook Pro

### ISSUE THREAD

**Issue by Hassanbalochh** [SafeExamBrowser/seb-mac#80]
I want Safe Browser version 2.4.1 for Macbook Pro please suggest link

**Comment by danschlet** [comment]
The latest SEB version for macOS can be downloaded from our [download page](https://safeexambrowser.org/download_en.html#MacOSX) or directly here on GitHub from the seb-mac [Releases](https://github.com/SafeExamBrowser/seb-mac/releases) page.

As you would have seen if you looked there, there is no version 2.4.1 for Mac. The latest final release is 2.2.2 currently and the final version of 2.3 will be released in the next days.
