### ISSUE TITLE
Do SEB Works With M1 Macbooks ?

### ISSUE THREAD

**Issue by mohalart** [SafeExamBrowser/seb-mac#81]
I am planning to buy a M1 mac, but I need to know if SEB works with M1 Macbooks with or without rosetta 2.

**Comment by danschlet** [comment]
The current version runs well in Rosetta 2, but the new 2.3 version is native on Apple Silicon:
https://github.com/SafeExamBrowser/seb-mac/releases/tag/2.3RC
