### ISSUE TITLE
Enable Zoom with SEB for proctoring

### ISSUE THREAD

**Issue by hernanjn** [SafeExamBrowser/seb-mac#82]
Hi!
Exist any way to allow use Zoom during an exam with SEB for teacher proctoring on MacOS?
Thanks!!!!

**Comment by danschlet** [comment]
Please check following threads in our other forum:
https://sourceforge.net/p/seb/support-requests/100/
https://sourceforge.net/p/seb/discussion/844844/thread/2e8caa51f3/?limit=25&page=1

In short: You can start and connect the Zoom app before starting SEB, but it can only run in the background and cannot be accessed during the exam (for reconnection or similar). The screen sharing feature of Zoom cannot be used together with the current versions of SEB for macOS. See the above discussions for the required settings.
