### ISSUE TITLE
How to use Zoom Meeting on SEB macOS

### ISSUE THREAD

**Issue by jonbeh57** [SafeExamBrowser/seb-mac#85]
Is there any chance to use Zoom Meeting on SEB macOS 11.3?

**Comment by danschlet** [comment]
There are some threads in our other forums, for example
https://sourceforge.net/p/seb/discussion/844844/thread/2e8caa51f3/?limit=25&page=1

You can use the search field on our SourceForge site to search the Discussion and Support Requests (under Tickets) sections for "Zoom" to find previous discussions.
