### ISSUE TITLE
Greetings I have a problem save exam browser

### ISSUE THREAD

**Issue by ivanBrezo** [SafeExamBrowser/seb-mac#89]
I have problem with save exam browser when I downloaded computer repeat me that this application is not available to my region I am from Bosna and Hercegovina

**Comment by danschlet** [comment]
Which version are you talking about and which link(s) did you use to download? The iOS version (2.1.17) in the App Store is available in Bosnia and Herzegowina, according to the App Store settings (https://itunes.apple.com/app/safeexambrowser/id1155002964?mt=8). 

The Mac and Windows versions are downloadable from SourceForge and GitHub (see the big blue button and the link for GitHub underneath on the page https://safeexambrowser.org/download_en.html). I'm not aware if SourceForge or GitHub would restrict the availability of software.

**Comment by danschlet** [comment]
Any update on this?
