### ISSUE TITLE
Forced closed and not responding in macbook with apple silicon (m1 chip)

### ISSUE THREAD

**Issue by tzara26** [SafeExamBrowser/seb-mac#90]
hello, i have an issue on my macbook air m1, when i use safe exam browser on my laptop, the seb sometimes closed byitself or not responding, and also when i click the answer sometimes its doesnt input the answer

**Comment by danschlet** [comment]
Are you using the latest version 2.3.2? Can you post the text of the system's crash report (macOS displays that after an app crashed)?

**Comment by danschlet** [comment]
If no further feedback received, this issue will be closed.

**Comment by omersanli17** [comment]
In our exams on Moodle, students face to crash report when python editor (external link) is open. 
Note. Latest version of SEB and MacOS

<img width="1440" alt="Ekran Resmi 2021-12-13 19 34 21" src="https://user-images.githubusercontent.com/29977489/147474170-ceb7bb0e-8a28-4f14-8321-2f65b1d4e118.png">

**Comment by danschlet** [comment]
This issue should be fixed in the [3.2 preview version](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.2pre5). If you can test if it still happens with that version, please let us know.
