### ISSUE TITLE
Are DMG files for previous versions no longer available?

### ISSUE THREAD

**Issue by joseluisrc** [SafeExamBrowser/seb-mac#93]
Until recently, DMGs for Mac OS X were available for all previous versions of SEB. Today I noticed that they're no longer available. Is this a decision made by Github or the Safe Exam Browser team?

Thanks!

**Comment by danschlet** [comment]
As mentioned on this page: https://safeexambrowser.org/download_releases_en.html and in several news post in the past months, we are no longer providing outdated SEB versions for download. We are only supporting the latest SEB version and will remove all older SEB versions after a grace period. Please adjust your procedures accordingly. Only with updated SEB versions you can achieve the best possible security and stability of e-assessments. Therefore you have to keep your exam environment up to date, there is no alternative to regular updates.

From time to time we are getting support requests or bug reports for outdated versions, which we have to reject, as we are supporting only the latest SEB versions. People don't follow our instruction "Before asking any support question or reporting a bug, please install the latest SEB version and try to reproduce the issue with the most recent version.". Therefore we try to prevent people downloading and using old versions by removing those downloads.
