### ISSUE TITLE
MAC SEB: Within VDI there is continuous key pressed after a few minutes

### ISSUE THREAD

**Issue by mkisready** [SafeExamBrowser/seb-mac#94]
We are using SEB (MAC) to provide access to Windows VDI. The user is able to get to the VDI. But after a few minutes there is continious non stop key press seen on the VDI whenever the person tries to type something (eg: aaaaaaaa...). This issue is observed only when we use SEB on a MAC, for Windows SEB we dont see this issue.

Is there anything that needs to be done to overcome this?

Regards
MK

**Comment by mkisready** [comment]
Issue observed on all MAC laptops what we have used till now.

MAC with SEB > RDP to Windows > Begin typing. Issue seen in few seconds
SEB version 2.3.2 and older ones. 
MAC version OS Big Sur and older ones.
VDI Windows 7 & 10

Here is a 4 second video of the same:
https://user-images.githubusercontent.com/85229648/120470569-4f365f80-c3c1-11eb-978a-cffc34d47099.mp4

**Comment by danschlet** [comment]
Can you please give us more information about your environment, which VDI solution and what kind of client are you using? Your question is way too general, I can't give you any answer other than I don't know about any issues with keyboard input in the Mac version. SEB for macOS doesn't include code to do anything with keyboard input, therefore this sounds like an issue of that VDI solution, maybe a compatibility issue with the old WebKit engine currently used in SEB. SEB 3.0 for macOS (should be available until end of June) will use the modern WebKit browser engine (WKWebView), which will increase web compatibility (should be mostly identical with current Safari versions).

Best is if we can reproduce issues, for that we would need a testing access to your system.

**Comment by mkisready** [comment]
Hi,

Sure. Is there a secure place where i can share the SEB and the credentials?

**Comment by mkisready** [comment]
Hi,

Sure. Is there a secure place where i can share the SEB and the credentials?

VDI solution uses Guacamole that links to a Windows 7 & 10. The key press
issues are seen only when we run the SEB on MAC, on Windows the SEB works
perfectly.
The issue can be reproduced everytime once we start typing anything on the
VDI.

Regards,
MK

**Comment by mkisready** [comment]
team any update? let me know where it can share the credentials and SEB.

**Comment by mkisready** [comment]
You can access the testing system using the attached SEB. You will need firefox installed.
1. When you double click the SEB enter password - cisco
2. Select VDI 1
3. Credentials : sebtest123/AHNtBnrK
4. Open and browser or file and keep tying for a few mins. Issue will be reproduced.

Let me know if you need anything else. Thanks.

[SEBExamFile_v3.4.seb.zip](https://github.com/SafeExamBrowser/seb-mac/files/6639361/SEBExamFile_v3.4.seb.zip)

**Comment by danschlet** [comment]
Thanks and sorry for the late answer. Most probably this issue is caused by the outdated browser engine (the classic WebView) in the current versions of SEB for macOS. I expect that Guacamole will work correctly with the newer browser engine (WKWebView) in SEB 3.0. I should be able to test it next week when there is a first developer build or 3.0 for macOS. I will let you know.

**Comment by mkisready** [comment]
Thank you. Will wait for your update.

**Comment by mkisready** [comment]
Team, Any update on this issue? The 3.2.0 for windows seems to be out now. Can you let me know when would this release be out for mac as well? Will it have the fix?

**Comment by mkisready** [comment]
Team, Any update on this issue & next release?

**Comment by danschlet** [comment]
You can test your issue now with the [release candidate of SEB 3.0](https://github.com/SafeExamBrowser/seb-mac/releases/tag/3.0rc) for macOS.

**Comment by mkisready** [comment]
Hi Daniel,

Thanks, we will test it to see if the issue is fixed.

Thanks
MK

**Comment by mkisready** [comment]
Hi Daniel,

Our team tested SEB 3.0 on macOS. The key press issue seems to be fixed in this release.
Thanks a lot for helping fix this issue!! Really appreciate it!!

Thanks 
MK
